// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: res_arena.proto

package proto.res;

public final class ResArena {
  private ResArena() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Arena extends
      com.google.protobuf.GeneratedMessage {
    // Use Arena.newBuilder() to construct.
    private Arena() {
      initFields();
    }
    private Arena(boolean noInit) {}
    
    private static final Arena defaultInstance;
    public static Arena getDefaultInstance() {
      return defaultInstance;
    }
    
    public Arena getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResArena.internal_static_Arena_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResArena.internal_static_Arena_fieldAccessorTable;
    }
    
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional .LogicalGame logicalGame = 2;
    public static final int LOGICALGAME_FIELD_NUMBER = 2;
    private boolean hasLogicalGame;
    private proto.response.ResGame.LogicalGame logicalGame_;
    public boolean hasLogicalGame() { return hasLogicalGame; }
    public proto.response.ResGame.LogicalGame getLogicalGame() { return logicalGame_; }
    
    // optional .PhysicalGame physicalGame = 3;
    public static final int PHYSICALGAME_FIELD_NUMBER = 3;
    private boolean hasPhysicalGame;
    private proto.response.ResGame.PhysicalGame physicalGame_;
    public boolean hasPhysicalGame() { return hasPhysicalGame; }
    public proto.response.ResGame.PhysicalGame getPhysicalGame() { return physicalGame_; }
    
    // optional .Map gameMap = 4;
    public static final int GAMEMAP_FIELD_NUMBER = 4;
    private boolean hasGameMap;
    private proto.response.ResGame.Map gameMap_;
    public boolean hasGameMap() { return hasGameMap; }
    public proto.response.ResGame.Map getGameMap() { return gameMap_; }
    
    // optional string status = 5;
    public static final int STATUS_FIELD_NUMBER = 5;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    // repeated .ArenaSlot players = 6;
    public static final int PLAYERS_FIELD_NUMBER = 6;
    private java.util.List<proto.res.ResArena.ArenaSlot> players_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.res.ResArena.ArenaSlot> getPlayersList() {
      return players_;
    }
    public int getPlayersCount() { return players_.size(); }
    public proto.res.ResArena.ArenaSlot getPlayers(int index) {
      return players_.get(index);
    }
    
    // repeated .StringDictItem attributes = 7;
    public static final int ATTRIBUTES_FIELD_NUMBER = 7;
    private java.util.List<proto.util.Util.StringDictItem> attributes_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.util.Util.StringDictItem> getAttributesList() {
      return attributes_;
    }
    public int getAttributesCount() { return attributes_.size(); }
    public proto.util.Util.StringDictItem getAttributes(int index) {
      return attributes_.get(index);
    }
    
    // optional string name = 8;
    public static final int NAME_FIELD_NUMBER = 8;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .BattleForce forces = 9;
    public static final int FORCES_FIELD_NUMBER = 9;
    private java.util.List<proto.res.ResArena.BattleForce> forces_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.res.ResArena.BattleForce> getForcesList() {
      return forces_;
    }
    public int getForcesCount() { return forces_.size(); }
    public proto.res.ResArena.BattleForce getForces(int index) {
      return forces_.get(index);
    }
    
    // optional .ChoiceFieldList userAttributeDefinition = 10;
    public static final int USERATTRIBUTEDEFINITION_FIELD_NUMBER = 10;
    private boolean hasUserAttributeDefinition;
    private proto.res.ResForm.ChoiceFieldList userAttributeDefinition_;
    public boolean hasUserAttributeDefinition() { return hasUserAttributeDefinition; }
    public proto.res.ResForm.ChoiceFieldList getUserAttributeDefinition() { return userAttributeDefinition_; }
    
    // optional bool private_flag = 11;
    public static final int PRIVATE_FLAG_FIELD_NUMBER = 11;
    private boolean hasPrivateFlag;
    private boolean privateFlag_ = false;
    public boolean hasPrivateFlag() { return hasPrivateFlag; }
    public boolean getPrivateFlag() { return privateFlag_; }
    
    // optional uint32 chatgroup = 12;
    public static final int CHATGROUP_FIELD_NUMBER = 12;
    private boolean hasChatgroup;
    private int chatgroup_ = 0;
    public boolean hasChatgroup() { return hasChatgroup; }
    public int getChatgroup() { return chatgroup_; }
    
    // repeated string my_actions = 13;
    public static final int MY_ACTIONS_FIELD_NUMBER = 13;
    private java.util.List<java.lang.String> myActions_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getMyActionsList() {
      return myActions_;
    }
    public int getMyActionsCount() { return myActions_.size(); }
    public java.lang.String getMyActions(int index) {
      return myActions_.get(index);
    }
    
    // optional string mode = 14;
    public static final int MODE_FIELD_NUMBER = 14;
    private boolean hasMode;
    private java.lang.String mode_ = "";
    public boolean hasMode() { return hasMode; }
    public java.lang.String getMode() { return mode_; }
    
    // optional string uuid = 15;
    public static final int UUID_FIELD_NUMBER = 15;
    private boolean hasUuid;
    private java.lang.String uuid_ = "";
    public boolean hasUuid() { return hasUuid; }
    public java.lang.String getUuid() { return uuid_; }
    
    // optional string type = 20;
    public static final int TYPE_FIELD_NUMBER = 20;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // optional string mappath = 16;
    public static final int MAPPATH_FIELD_NUMBER = 16;
    private boolean hasMappath;
    private java.lang.String mappath_ = "";
    public boolean hasMappath() { return hasMappath; }
    public java.lang.String getMappath() { return mappath_; }
    
    // optional string gamepath = 17;
    public static final int GAMEPATH_FIELD_NUMBER = 17;
    private boolean hasGamepath;
    private java.lang.String gamepath_ = "";
    public boolean hasGamepath() { return hasGamepath; }
    public java.lang.String getGamepath() { return gamepath_; }
    
    // optional uint32 hostID = 18;
    public static final int HOSTID_FIELD_NUMBER = 18;
    private boolean hasHostID;
    private int hostID_ = 0;
    public boolean hasHostID() { return hasHostID; }
    public int getHostID() { return hostID_; }
    
    // optional uint32 whoAmI = 19;
    public static final int WHOAMI_FIELD_NUMBER = 19;
    private boolean hasWhoAmI;
    private int whoAmI_ = 0;
    public boolean hasWhoAmI() { return hasWhoAmI; }
    public int getWhoAmI() { return whoAmI_; }
    
    // optional string event_name = 21;
    public static final int EVENT_NAME_FIELD_NUMBER = 21;
    private boolean hasEventName;
    private java.lang.String eventName_ = "";
    public boolean hasEventName() { return hasEventName; }
    public java.lang.String getEventName() { return eventName_; }
    
    // optional string event_id = 22;
    public static final int EVENT_ID_FIELD_NUMBER = 22;
    private boolean hasEventId;
    private java.lang.String eventId_ = "";
    public boolean hasEventId() { return hasEventId; }
    public java.lang.String getEventId() { return eventId_; }
    
    private void initFields() {
      logicalGame_ = proto.response.ResGame.LogicalGame.getDefaultInstance();
      physicalGame_ = proto.response.ResGame.PhysicalGame.getDefaultInstance();
      gameMap_ = proto.response.ResGame.Map.getDefaultInstance();
      userAttributeDefinition_ = proto.res.ResForm.ChoiceFieldList.getDefaultInstance();
    }
    public static proto.res.ResArena.Arena parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.Arena parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.Arena parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.Arena parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.Arena parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.Arena parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.Arena parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.Arena parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.Arena parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.Arena parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResArena.Arena prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResArena.Arena result;
      
      // Construct using proto.res.ResArena.Arena.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResArena.Arena();
        return builder;
      }
      
      protected proto.res.ResArena.Arena internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResArena.Arena();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResArena.Arena.getDescriptor();
      }
      
      public proto.res.ResArena.Arena getDefaultInstanceForType() {
        return proto.res.ResArena.Arena.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResArena.Arena build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResArena.Arena buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResArena.Arena buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.players_ != java.util.Collections.EMPTY_LIST) {
          result.players_ =
            java.util.Collections.unmodifiableList(result.players_);
        }
        if (result.attributes_ != java.util.Collections.EMPTY_LIST) {
          result.attributes_ =
            java.util.Collections.unmodifiableList(result.attributes_);
        }
        if (result.forces_ != java.util.Collections.EMPTY_LIST) {
          result.forces_ =
            java.util.Collections.unmodifiableList(result.forces_);
        }
        if (result.myActions_ != java.util.Collections.EMPTY_LIST) {
          result.myActions_ =
            java.util.Collections.unmodifiableList(result.myActions_);
        }
        proto.res.ResArena.Arena returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional .LogicalGame logicalGame = 2;
      public boolean hasLogicalGame() {
        return result.hasLogicalGame();
      }
      public proto.response.ResGame.LogicalGame getLogicalGame() {
        return result.getLogicalGame();
      }
      public Builder setLogicalGame(proto.response.ResGame.LogicalGame value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLogicalGame = true;
        result.logicalGame_ = value;
        return this;
      }
      public Builder setLogicalGame(proto.response.ResGame.LogicalGame.Builder builderForValue) {
        result.hasLogicalGame = true;
        result.logicalGame_ = builderForValue.build();
        return this;
      }
      public Builder mergeLogicalGame(proto.response.ResGame.LogicalGame value) {
        if (result.hasLogicalGame() &&
            result.logicalGame_ != proto.response.ResGame.LogicalGame.getDefaultInstance()) {
          result.logicalGame_ =
            proto.response.ResGame.LogicalGame.newBuilder(result.logicalGame_).mergeFrom(value).buildPartial();
        } else {
          result.logicalGame_ = value;
        }
        result.hasLogicalGame = true;
        return this;
      }
      public Builder clearLogicalGame() {
        result.hasLogicalGame = false;
        result.logicalGame_ = proto.response.ResGame.LogicalGame.getDefaultInstance();
        return this;
      }
      
      // optional .PhysicalGame physicalGame = 3;
      public boolean hasPhysicalGame() {
        return result.hasPhysicalGame();
      }
      public proto.response.ResGame.PhysicalGame getPhysicalGame() {
        return result.getPhysicalGame();
      }
      public Builder setPhysicalGame(proto.response.ResGame.PhysicalGame value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPhysicalGame = true;
        result.physicalGame_ = value;
        return this;
      }
      public Builder setPhysicalGame(proto.response.ResGame.PhysicalGame.Builder builderForValue) {
        result.hasPhysicalGame = true;
        result.physicalGame_ = builderForValue.build();
        return this;
      }
      public Builder mergePhysicalGame(proto.response.ResGame.PhysicalGame value) {
        if (result.hasPhysicalGame() &&
            result.physicalGame_ != proto.response.ResGame.PhysicalGame.getDefaultInstance()) {
          result.physicalGame_ =
            proto.response.ResGame.PhysicalGame.newBuilder(result.physicalGame_).mergeFrom(value).buildPartial();
        } else {
          result.physicalGame_ = value;
        }
        result.hasPhysicalGame = true;
        return this;
      }
      public Builder clearPhysicalGame() {
        result.hasPhysicalGame = false;
        result.physicalGame_ = proto.response.ResGame.PhysicalGame.getDefaultInstance();
        return this;
      }
      
      // optional .Map gameMap = 4;
      public boolean hasGameMap() {
        return result.hasGameMap();
      }
      public proto.response.ResGame.Map getGameMap() {
        return result.getGameMap();
      }
      public Builder setGameMap(proto.response.ResGame.Map value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameMap = true;
        result.gameMap_ = value;
        return this;
      }
      public Builder setGameMap(proto.response.ResGame.Map.Builder builderForValue) {
        result.hasGameMap = true;
        result.gameMap_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameMap(proto.response.ResGame.Map value) {
        if (result.hasGameMap() &&
            result.gameMap_ != proto.response.ResGame.Map.getDefaultInstance()) {
          result.gameMap_ =
            proto.response.ResGame.Map.newBuilder(result.gameMap_).mergeFrom(value).buildPartial();
        } else {
          result.gameMap_ = value;
        }
        result.hasGameMap = true;
        return this;
      }
      public Builder clearGameMap() {
        result.hasGameMap = false;
        result.gameMap_ = proto.response.ResGame.Map.getDefaultInstance();
        return this;
      }
      
      // optional string status = 5;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // repeated .ArenaSlot players = 6;
      public java.util.List<proto.res.ResArena.ArenaSlot> getPlayersList() {
        return java.util.Collections.unmodifiableList(result.players_);
      }
      public int getPlayersCount() {
        return result.getPlayersCount();
      }
      public proto.res.ResArena.ArenaSlot getPlayers(int index) {
        return result.getPlayers(index);
      }
      public Builder setPlayers(int index, proto.res.ResArena.ArenaSlot value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.players_.set(index, value);
        return this;
      }
      public Builder setPlayers(int index, proto.res.ResArena.ArenaSlot.Builder builderForValue) {
        result.players_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPlayers(proto.res.ResArena.ArenaSlot value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.players_.isEmpty()) {
          result.players_ = new java.util.ArrayList<proto.res.ResArena.ArenaSlot>();
        }
        result.players_.add(value);
        return this;
      }
      public Builder addPlayers(proto.res.ResArena.ArenaSlot.Builder builderForValue) {
        if (result.players_.isEmpty()) {
          result.players_ = new java.util.ArrayList<proto.res.ResArena.ArenaSlot>();
        }
        result.players_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPlayers(
          java.lang.Iterable<? extends proto.res.ResArena.ArenaSlot> values) {
        if (result.players_.isEmpty()) {
          result.players_ = new java.util.ArrayList<proto.res.ResArena.ArenaSlot>();
        }
        super.addAll(values, result.players_);
        return this;
      }
      public Builder clearPlayers() {
        result.players_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .StringDictItem attributes = 7;
      public java.util.List<proto.util.Util.StringDictItem> getAttributesList() {
        return java.util.Collections.unmodifiableList(result.attributes_);
      }
      public int getAttributesCount() {
        return result.getAttributesCount();
      }
      public proto.util.Util.StringDictItem getAttributes(int index) {
        return result.getAttributes(index);
      }
      public Builder setAttributes(int index, proto.util.Util.StringDictItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.attributes_.set(index, value);
        return this;
      }
      public Builder setAttributes(int index, proto.util.Util.StringDictItem.Builder builderForValue) {
        result.attributes_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAttributes(proto.util.Util.StringDictItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        result.attributes_.add(value);
        return this;
      }
      public Builder addAttributes(proto.util.Util.StringDictItem.Builder builderForValue) {
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        result.attributes_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAttributes(
          java.lang.Iterable<? extends proto.util.Util.StringDictItem> values) {
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        super.addAll(values, result.attributes_);
        return this;
      }
      public Builder clearAttributes() {
        result.attributes_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string name = 8;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .BattleForce forces = 9;
      public java.util.List<proto.res.ResArena.BattleForce> getForcesList() {
        return java.util.Collections.unmodifiableList(result.forces_);
      }
      public int getForcesCount() {
        return result.getForcesCount();
      }
      public proto.res.ResArena.BattleForce getForces(int index) {
        return result.getForces(index);
      }
      public Builder setForces(int index, proto.res.ResArena.BattleForce value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.forces_.set(index, value);
        return this;
      }
      public Builder setForces(int index, proto.res.ResArena.BattleForce.Builder builderForValue) {
        result.forces_.set(index, builderForValue.build());
        return this;
      }
      public Builder addForces(proto.res.ResArena.BattleForce value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.forces_.isEmpty()) {
          result.forces_ = new java.util.ArrayList<proto.res.ResArena.BattleForce>();
        }
        result.forces_.add(value);
        return this;
      }
      public Builder addForces(proto.res.ResArena.BattleForce.Builder builderForValue) {
        if (result.forces_.isEmpty()) {
          result.forces_ = new java.util.ArrayList<proto.res.ResArena.BattleForce>();
        }
        result.forces_.add(builderForValue.build());
        return this;
      }
      public Builder addAllForces(
          java.lang.Iterable<? extends proto.res.ResArena.BattleForce> values) {
        if (result.forces_.isEmpty()) {
          result.forces_ = new java.util.ArrayList<proto.res.ResArena.BattleForce>();
        }
        super.addAll(values, result.forces_);
        return this;
      }
      public Builder clearForces() {
        result.forces_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .ChoiceFieldList userAttributeDefinition = 10;
      public boolean hasUserAttributeDefinition() {
        return result.hasUserAttributeDefinition();
      }
      public proto.res.ResForm.ChoiceFieldList getUserAttributeDefinition() {
        return result.getUserAttributeDefinition();
      }
      public Builder setUserAttributeDefinition(proto.res.ResForm.ChoiceFieldList value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasUserAttributeDefinition = true;
        result.userAttributeDefinition_ = value;
        return this;
      }
      public Builder setUserAttributeDefinition(proto.res.ResForm.ChoiceFieldList.Builder builderForValue) {
        result.hasUserAttributeDefinition = true;
        result.userAttributeDefinition_ = builderForValue.build();
        return this;
      }
      public Builder mergeUserAttributeDefinition(proto.res.ResForm.ChoiceFieldList value) {
        if (result.hasUserAttributeDefinition() &&
            result.userAttributeDefinition_ != proto.res.ResForm.ChoiceFieldList.getDefaultInstance()) {
          result.userAttributeDefinition_ =
            proto.res.ResForm.ChoiceFieldList.newBuilder(result.userAttributeDefinition_).mergeFrom(value).buildPartial();
        } else {
          result.userAttributeDefinition_ = value;
        }
        result.hasUserAttributeDefinition = true;
        return this;
      }
      public Builder clearUserAttributeDefinition() {
        result.hasUserAttributeDefinition = false;
        result.userAttributeDefinition_ = proto.res.ResForm.ChoiceFieldList.getDefaultInstance();
        return this;
      }
      
      // optional bool private_flag = 11;
      public boolean hasPrivateFlag() {
        return result.hasPrivateFlag();
      }
      public boolean getPrivateFlag() {
        return result.getPrivateFlag();
      }
      public Builder setPrivateFlag(boolean value) {
        result.hasPrivateFlag = true;
        result.privateFlag_ = value;
        return this;
      }
      public Builder clearPrivateFlag() {
        result.hasPrivateFlag = false;
        result.privateFlag_ = false;
        return this;
      }
      
      // optional uint32 chatgroup = 12;
      public boolean hasChatgroup() {
        return result.hasChatgroup();
      }
      public int getChatgroup() {
        return result.getChatgroup();
      }
      public Builder setChatgroup(int value) {
        result.hasChatgroup = true;
        result.chatgroup_ = value;
        return this;
      }
      public Builder clearChatgroup() {
        result.hasChatgroup = false;
        result.chatgroup_ = 0;
        return this;
      }
      
      // repeated string my_actions = 13;
      public java.util.List<java.lang.String> getMyActionsList() {
        return java.util.Collections.unmodifiableList(result.myActions_);
      }
      public int getMyActionsCount() {
        return result.getMyActionsCount();
      }
      public java.lang.String getMyActions(int index) {
        return result.getMyActions(index);
      }
      public Builder setMyActions(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.myActions_.set(index, value);
        return this;
      }
      public Builder addMyActions(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.myActions_.isEmpty()) {
          result.myActions_ = new java.util.ArrayList<java.lang.String>();
        }
        result.myActions_.add(value);
        return this;
      }
      public Builder addAllMyActions(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.myActions_.isEmpty()) {
          result.myActions_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.myActions_);
        return this;
      }
      public Builder clearMyActions() {
        result.myActions_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string mode = 14;
      public boolean hasMode() {
        return result.hasMode();
      }
      public java.lang.String getMode() {
        return result.getMode();
      }
      public Builder setMode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMode = true;
        result.mode_ = value;
        return this;
      }
      public Builder clearMode() {
        result.hasMode = false;
        result.mode_ = getDefaultInstance().getMode();
        return this;
      }
      
      // optional string uuid = 15;
      public boolean hasUuid() {
        return result.hasUuid();
      }
      public java.lang.String getUuid() {
        return result.getUuid();
      }
      public Builder setUuid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUuid = true;
        result.uuid_ = value;
        return this;
      }
      public Builder clearUuid() {
        result.hasUuid = false;
        result.uuid_ = getDefaultInstance().getUuid();
        return this;
      }
      
      // optional string type = 20;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // optional string mappath = 16;
      public boolean hasMappath() {
        return result.hasMappath();
      }
      public java.lang.String getMappath() {
        return result.getMappath();
      }
      public Builder setMappath(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMappath = true;
        result.mappath_ = value;
        return this;
      }
      public Builder clearMappath() {
        result.hasMappath = false;
        result.mappath_ = getDefaultInstance().getMappath();
        return this;
      }
      
      // optional string gamepath = 17;
      public boolean hasGamepath() {
        return result.hasGamepath();
      }
      public java.lang.String getGamepath() {
        return result.getGamepath();
      }
      public Builder setGamepath(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGamepath = true;
        result.gamepath_ = value;
        return this;
      }
      public Builder clearGamepath() {
        result.hasGamepath = false;
        result.gamepath_ = getDefaultInstance().getGamepath();
        return this;
      }
      
      // optional uint32 hostID = 18;
      public boolean hasHostID() {
        return result.hasHostID();
      }
      public int getHostID() {
        return result.getHostID();
      }
      public Builder setHostID(int value) {
        result.hasHostID = true;
        result.hostID_ = value;
        return this;
      }
      public Builder clearHostID() {
        result.hasHostID = false;
        result.hostID_ = 0;
        return this;
      }
      
      // optional uint32 whoAmI = 19;
      public boolean hasWhoAmI() {
        return result.hasWhoAmI();
      }
      public int getWhoAmI() {
        return result.getWhoAmI();
      }
      public Builder setWhoAmI(int value) {
        result.hasWhoAmI = true;
        result.whoAmI_ = value;
        return this;
      }
      public Builder clearWhoAmI() {
        result.hasWhoAmI = false;
        result.whoAmI_ = 0;
        return this;
      }
      
      // optional string event_name = 21;
      public boolean hasEventName() {
        return result.hasEventName();
      }
      public java.lang.String getEventName() {
        return result.getEventName();
      }
      public Builder setEventName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEventName = true;
        result.eventName_ = value;
        return this;
      }
      public Builder clearEventName() {
        result.hasEventName = false;
        result.eventName_ = getDefaultInstance().getEventName();
        return this;
      }
      
      // optional string event_id = 22;
      public boolean hasEventId() {
        return result.hasEventId();
      }
      public java.lang.String getEventId() {
        return result.getEventId();
      }
      public Builder setEventId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEventId = true;
        result.eventId_ = value;
        return this;
      }
      public Builder clearEventId() {
        result.hasEventId = false;
        result.eventId_ = getDefaultInstance().getEventId();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Arena)
    }
    
    static {
      defaultInstance = new Arena(true);
      proto.res.ResArena.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Arena)
  }
  
  public static final class ArenaMini extends
      com.google.protobuf.GeneratedMessage {
    // Use ArenaMini.newBuilder() to construct.
    private ArenaMini() {
      initFields();
    }
    private ArenaMini(boolean noInit) {}
    
    private static final ArenaMini defaultInstance;
    public static ArenaMini getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArenaMini getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResArena.internal_static_ArenaMini_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResArena.internal_static_ArenaMini_fieldAccessorTable;
    }
    
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional .LogicalGame logicalGame = 2;
    public static final int LOGICALGAME_FIELD_NUMBER = 2;
    private boolean hasLogicalGame;
    private proto.response.ResGame.LogicalGame logicalGame_;
    public boolean hasLogicalGame() { return hasLogicalGame; }
    public proto.response.ResGame.LogicalGame getLogicalGame() { return logicalGame_; }
    
    // optional .PhysicalGame physicalGame = 3;
    public static final int PHYSICALGAME_FIELD_NUMBER = 3;
    private boolean hasPhysicalGame;
    private proto.response.ResGame.PhysicalGame physicalGame_;
    public boolean hasPhysicalGame() { return hasPhysicalGame; }
    public proto.response.ResGame.PhysicalGame getPhysicalGame() { return physicalGame_; }
    
    // optional .Map gameMap = 4;
    public static final int GAMEMAP_FIELD_NUMBER = 4;
    private boolean hasGameMap;
    private proto.response.ResGame.Map gameMap_;
    public boolean hasGameMap() { return hasGameMap; }
    public proto.response.ResGame.Map getGameMap() { return gameMap_; }
    
    // optional uint32 totalCount = 5;
    public static final int TOTALCOUNT_FIELD_NUMBER = 5;
    private boolean hasTotalCount;
    private int totalCount_ = 0;
    public boolean hasTotalCount() { return hasTotalCount; }
    public int getTotalCount() { return totalCount_; }
    
    // optional uint32 currentCount = 6;
    public static final int CURRENTCOUNT_FIELD_NUMBER = 6;
    private boolean hasCurrentCount;
    private int currentCount_ = 0;
    public boolean hasCurrentCount() { return hasCurrentCount; }
    public int getCurrentCount() { return currentCount_; }
    
    // optional string mode = 7;
    public static final int MODE_FIELD_NUMBER = 7;
    private boolean hasMode;
    private java.lang.String mode_ = "";
    public boolean hasMode() { return hasMode; }
    public java.lang.String getMode() { return mode_; }
    
    private void initFields() {
      logicalGame_ = proto.response.ResGame.LogicalGame.getDefaultInstance();
      physicalGame_ = proto.response.ResGame.PhysicalGame.getDefaultInstance();
      gameMap_ = proto.response.ResGame.Map.getDefaultInstance();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.ArenaMini parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.ArenaMini parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.ArenaMini parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResArena.ArenaMini prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResArena.ArenaMini result;
      
      // Construct using proto.res.ResArena.ArenaMini.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResArena.ArenaMini();
        return builder;
      }
      
      protected proto.res.ResArena.ArenaMini internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResArena.ArenaMini();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResArena.ArenaMini.getDescriptor();
      }
      
      public proto.res.ResArena.ArenaMini getDefaultInstanceForType() {
        return proto.res.ResArena.ArenaMini.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResArena.ArenaMini build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResArena.ArenaMini buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResArena.ArenaMini buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.res.ResArena.ArenaMini returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional .LogicalGame logicalGame = 2;
      public boolean hasLogicalGame() {
        return result.hasLogicalGame();
      }
      public proto.response.ResGame.LogicalGame getLogicalGame() {
        return result.getLogicalGame();
      }
      public Builder setLogicalGame(proto.response.ResGame.LogicalGame value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLogicalGame = true;
        result.logicalGame_ = value;
        return this;
      }
      public Builder setLogicalGame(proto.response.ResGame.LogicalGame.Builder builderForValue) {
        result.hasLogicalGame = true;
        result.logicalGame_ = builderForValue.build();
        return this;
      }
      public Builder mergeLogicalGame(proto.response.ResGame.LogicalGame value) {
        if (result.hasLogicalGame() &&
            result.logicalGame_ != proto.response.ResGame.LogicalGame.getDefaultInstance()) {
          result.logicalGame_ =
            proto.response.ResGame.LogicalGame.newBuilder(result.logicalGame_).mergeFrom(value).buildPartial();
        } else {
          result.logicalGame_ = value;
        }
        result.hasLogicalGame = true;
        return this;
      }
      public Builder clearLogicalGame() {
        result.hasLogicalGame = false;
        result.logicalGame_ = proto.response.ResGame.LogicalGame.getDefaultInstance();
        return this;
      }
      
      // optional .PhysicalGame physicalGame = 3;
      public boolean hasPhysicalGame() {
        return result.hasPhysicalGame();
      }
      public proto.response.ResGame.PhysicalGame getPhysicalGame() {
        return result.getPhysicalGame();
      }
      public Builder setPhysicalGame(proto.response.ResGame.PhysicalGame value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPhysicalGame = true;
        result.physicalGame_ = value;
        return this;
      }
      public Builder setPhysicalGame(proto.response.ResGame.PhysicalGame.Builder builderForValue) {
        result.hasPhysicalGame = true;
        result.physicalGame_ = builderForValue.build();
        return this;
      }
      public Builder mergePhysicalGame(proto.response.ResGame.PhysicalGame value) {
        if (result.hasPhysicalGame() &&
            result.physicalGame_ != proto.response.ResGame.PhysicalGame.getDefaultInstance()) {
          result.physicalGame_ =
            proto.response.ResGame.PhysicalGame.newBuilder(result.physicalGame_).mergeFrom(value).buildPartial();
        } else {
          result.physicalGame_ = value;
        }
        result.hasPhysicalGame = true;
        return this;
      }
      public Builder clearPhysicalGame() {
        result.hasPhysicalGame = false;
        result.physicalGame_ = proto.response.ResGame.PhysicalGame.getDefaultInstance();
        return this;
      }
      
      // optional .Map gameMap = 4;
      public boolean hasGameMap() {
        return result.hasGameMap();
      }
      public proto.response.ResGame.Map getGameMap() {
        return result.getGameMap();
      }
      public Builder setGameMap(proto.response.ResGame.Map value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameMap = true;
        result.gameMap_ = value;
        return this;
      }
      public Builder setGameMap(proto.response.ResGame.Map.Builder builderForValue) {
        result.hasGameMap = true;
        result.gameMap_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameMap(proto.response.ResGame.Map value) {
        if (result.hasGameMap() &&
            result.gameMap_ != proto.response.ResGame.Map.getDefaultInstance()) {
          result.gameMap_ =
            proto.response.ResGame.Map.newBuilder(result.gameMap_).mergeFrom(value).buildPartial();
        } else {
          result.gameMap_ = value;
        }
        result.hasGameMap = true;
        return this;
      }
      public Builder clearGameMap() {
        result.hasGameMap = false;
        result.gameMap_ = proto.response.ResGame.Map.getDefaultInstance();
        return this;
      }
      
      // optional uint32 totalCount = 5;
      public boolean hasTotalCount() {
        return result.hasTotalCount();
      }
      public int getTotalCount() {
        return result.getTotalCount();
      }
      public Builder setTotalCount(int value) {
        result.hasTotalCount = true;
        result.totalCount_ = value;
        return this;
      }
      public Builder clearTotalCount() {
        result.hasTotalCount = false;
        result.totalCount_ = 0;
        return this;
      }
      
      // optional uint32 currentCount = 6;
      public boolean hasCurrentCount() {
        return result.hasCurrentCount();
      }
      public int getCurrentCount() {
        return result.getCurrentCount();
      }
      public Builder setCurrentCount(int value) {
        result.hasCurrentCount = true;
        result.currentCount_ = value;
        return this;
      }
      public Builder clearCurrentCount() {
        result.hasCurrentCount = false;
        result.currentCount_ = 0;
        return this;
      }
      
      // optional string mode = 7;
      public boolean hasMode() {
        return result.hasMode();
      }
      public java.lang.String getMode() {
        return result.getMode();
      }
      public Builder setMode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMode = true;
        result.mode_ = value;
        return this;
      }
      public Builder clearMode() {
        result.hasMode = false;
        result.mode_ = getDefaultInstance().getMode();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ArenaMini)
    }
    
    static {
      defaultInstance = new ArenaMini(true);
      proto.res.ResArena.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ArenaMini)
  }
  
  public static final class BattleForce extends
      com.google.protobuf.GeneratedMessage {
    // Use BattleForce.newBuilder() to construct.
    private BattleForce() {
      initFields();
    }
    private BattleForce(boolean noInit) {}
    
    private static final BattleForce defaultInstance;
    public static BattleForce getDefaultInstance() {
      return defaultInstance;
    }
    
    public BattleForce getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResArena.internal_static_BattleForce_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResArena.internal_static_BattleForce_fieldAccessorTable;
    }
    
    // optional uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string label = 2;
    public static final int LABEL_FIELD_NUMBER = 2;
    private boolean hasLabel;
    private java.lang.String label_ = "";
    public boolean hasLabel() { return hasLabel; }
    public java.lang.String getLabel() { return label_; }
    
    // optional uint32 partyID = 10;
    public static final int PARTYID_FIELD_NUMBER = 10;
    private boolean hasPartyID;
    private int partyID_ = 0;
    public boolean hasPartyID() { return hasPartyID; }
    public int getPartyID() { return partyID_; }
    
    // optional string status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    // optional uint32 leaderID = 11;
    public static final int LEADERID_FIELD_NUMBER = 11;
    private boolean hasLeaderID;
    private int leaderID_ = 0;
    public boolean hasLeaderID() { return hasLeaderID; }
    public int getLeaderID() { return leaderID_; }
    
    // repeated .StringDictItem attributes = 4;
    public static final int ATTRIBUTES_FIELD_NUMBER = 4;
    private java.util.List<proto.util.Util.StringDictItem> attributes_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.util.Util.StringDictItem> getAttributesList() {
      return attributes_;
    }
    public int getAttributesCount() { return attributes_.size(); }
    public proto.util.Util.StringDictItem getAttributes(int index) {
      return attributes_.get(index);
    }
    
    private void initFields() {
    }
    public static proto.res.ResArena.BattleForce parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.BattleForce parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.BattleForce parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.BattleForce parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResArena.BattleForce prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResArena.BattleForce result;
      
      // Construct using proto.res.ResArena.BattleForce.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResArena.BattleForce();
        return builder;
      }
      
      protected proto.res.ResArena.BattleForce internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResArena.BattleForce();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResArena.BattleForce.getDescriptor();
      }
      
      public proto.res.ResArena.BattleForce getDefaultInstanceForType() {
        return proto.res.ResArena.BattleForce.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResArena.BattleForce build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResArena.BattleForce buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResArena.BattleForce buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.attributes_ != java.util.Collections.EMPTY_LIST) {
          result.attributes_ =
            java.util.Collections.unmodifiableList(result.attributes_);
        }
        proto.res.ResArena.BattleForce returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string label = 2;
      public boolean hasLabel() {
        return result.hasLabel();
      }
      public java.lang.String getLabel() {
        return result.getLabel();
      }
      public Builder setLabel(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLabel = true;
        result.label_ = value;
        return this;
      }
      public Builder clearLabel() {
        result.hasLabel = false;
        result.label_ = getDefaultInstance().getLabel();
        return this;
      }
      
      // optional uint32 partyID = 10;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public int getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(int value) {
        result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = 0;
        return this;
      }
      
      // optional string status = 3;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // optional uint32 leaderID = 11;
      public boolean hasLeaderID() {
        return result.hasLeaderID();
      }
      public int getLeaderID() {
        return result.getLeaderID();
      }
      public Builder setLeaderID(int value) {
        result.hasLeaderID = true;
        result.leaderID_ = value;
        return this;
      }
      public Builder clearLeaderID() {
        result.hasLeaderID = false;
        result.leaderID_ = 0;
        return this;
      }
      
      // repeated .StringDictItem attributes = 4;
      public java.util.List<proto.util.Util.StringDictItem> getAttributesList() {
        return java.util.Collections.unmodifiableList(result.attributes_);
      }
      public int getAttributesCount() {
        return result.getAttributesCount();
      }
      public proto.util.Util.StringDictItem getAttributes(int index) {
        return result.getAttributes(index);
      }
      public Builder setAttributes(int index, proto.util.Util.StringDictItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.attributes_.set(index, value);
        return this;
      }
      public Builder setAttributes(int index, proto.util.Util.StringDictItem.Builder builderForValue) {
        result.attributes_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAttributes(proto.util.Util.StringDictItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        result.attributes_.add(value);
        return this;
      }
      public Builder addAttributes(proto.util.Util.StringDictItem.Builder builderForValue) {
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        result.attributes_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAttributes(
          java.lang.Iterable<? extends proto.util.Util.StringDictItem> values) {
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        super.addAll(values, result.attributes_);
        return this;
      }
      public Builder clearAttributes() {
        result.attributes_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BattleForce)
    }
    
    static {
      defaultInstance = new BattleForce(true);
      proto.res.ResArena.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BattleForce)
  }
  
  public static final class ArenaSlot extends
      com.google.protobuf.GeneratedMessage {
    // Use ArenaSlot.newBuilder() to construct.
    private ArenaSlot() {
      initFields();
    }
    private ArenaSlot(boolean noInit) {}
    
    private static final ArenaSlot defaultInstance;
    public static ArenaSlot getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArenaSlot getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResArena.internal_static_ArenaSlot_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResArena.internal_static_ArenaSlot_fieldAccessorTable;
    }
    
    // optional .UserModel user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private boolean hasUser;
    private proto.response.ResUser.UserModel user_;
    public boolean hasUser() { return hasUser; }
    public proto.response.ResUser.UserModel getUser() { return user_; }
    
    // optional uint32 position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private boolean hasPosition;
    private int position_ = 0;
    public boolean hasPosition() { return hasPosition; }
    public int getPosition() { return position_; }
    
    // optional uint32 forceID = 3;
    public static final int FORCEID_FIELD_NUMBER = 3;
    private boolean hasForceID;
    private int forceID_ = 0;
    public boolean hasForceID() { return hasForceID; }
    public int getForceID() { return forceID_; }
    
    // repeated .StringDictItem attributes = 4;
    public static final int ATTRIBUTES_FIELD_NUMBER = 4;
    private java.util.List<proto.util.Util.StringDictItem> attributes_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.util.Util.StringDictItem> getAttributesList() {
      return attributes_;
    }
    public int getAttributesCount() { return attributes_.size(); }
    public proto.util.Util.StringDictItem getAttributes(int index) {
      return attributes_.get(index);
    }
    
    // optional bool enabled = 5;
    public static final int ENABLED_FIELD_NUMBER = 5;
    private boolean hasEnabled;
    private boolean enabled_ = false;
    public boolean hasEnabled() { return hasEnabled; }
    public boolean getEnabled() { return enabled_; }
    
    // optional bool ready = 6;
    public static final int READY_FIELD_NUMBER = 6;
    private boolean hasReady;
    private boolean ready_ = false;
    public boolean hasReady() { return hasReady; }
    public boolean getReady() { return ready_; }
    
    private void initFields() {
      user_ = proto.response.ResUser.UserModel.getDefaultInstance();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.ArenaSlot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.ArenaSlot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResArena.ArenaSlot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResArena.ArenaSlot result;
      
      // Construct using proto.res.ResArena.ArenaSlot.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResArena.ArenaSlot();
        return builder;
      }
      
      protected proto.res.ResArena.ArenaSlot internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResArena.ArenaSlot();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResArena.ArenaSlot.getDescriptor();
      }
      
      public proto.res.ResArena.ArenaSlot getDefaultInstanceForType() {
        return proto.res.ResArena.ArenaSlot.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResArena.ArenaSlot build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResArena.ArenaSlot buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResArena.ArenaSlot buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.attributes_ != java.util.Collections.EMPTY_LIST) {
          result.attributes_ =
            java.util.Collections.unmodifiableList(result.attributes_);
        }
        proto.res.ResArena.ArenaSlot returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional .UserModel user = 1;
      public boolean hasUser() {
        return result.hasUser();
      }
      public proto.response.ResUser.UserModel getUser() {
        return result.getUser();
      }
      public Builder setUser(proto.response.ResUser.UserModel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasUser = true;
        result.user_ = value;
        return this;
      }
      public Builder setUser(proto.response.ResUser.UserModel.Builder builderForValue) {
        result.hasUser = true;
        result.user_ = builderForValue.build();
        return this;
      }
      public Builder mergeUser(proto.response.ResUser.UserModel value) {
        if (result.hasUser() &&
            result.user_ != proto.response.ResUser.UserModel.getDefaultInstance()) {
          result.user_ =
            proto.response.ResUser.UserModel.newBuilder(result.user_).mergeFrom(value).buildPartial();
        } else {
          result.user_ = value;
        }
        result.hasUser = true;
        return this;
      }
      public Builder clearUser() {
        result.hasUser = false;
        result.user_ = proto.response.ResUser.UserModel.getDefaultInstance();
        return this;
      }
      
      // optional uint32 position = 2;
      public boolean hasPosition() {
        return result.hasPosition();
      }
      public int getPosition() {
        return result.getPosition();
      }
      public Builder setPosition(int value) {
        result.hasPosition = true;
        result.position_ = value;
        return this;
      }
      public Builder clearPosition() {
        result.hasPosition = false;
        result.position_ = 0;
        return this;
      }
      
      // optional uint32 forceID = 3;
      public boolean hasForceID() {
        return result.hasForceID();
      }
      public int getForceID() {
        return result.getForceID();
      }
      public Builder setForceID(int value) {
        result.hasForceID = true;
        result.forceID_ = value;
        return this;
      }
      public Builder clearForceID() {
        result.hasForceID = false;
        result.forceID_ = 0;
        return this;
      }
      
      // repeated .StringDictItem attributes = 4;
      public java.util.List<proto.util.Util.StringDictItem> getAttributesList() {
        return java.util.Collections.unmodifiableList(result.attributes_);
      }
      public int getAttributesCount() {
        return result.getAttributesCount();
      }
      public proto.util.Util.StringDictItem getAttributes(int index) {
        return result.getAttributes(index);
      }
      public Builder setAttributes(int index, proto.util.Util.StringDictItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.attributes_.set(index, value);
        return this;
      }
      public Builder setAttributes(int index, proto.util.Util.StringDictItem.Builder builderForValue) {
        result.attributes_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAttributes(proto.util.Util.StringDictItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        result.attributes_.add(value);
        return this;
      }
      public Builder addAttributes(proto.util.Util.StringDictItem.Builder builderForValue) {
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        result.attributes_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAttributes(
          java.lang.Iterable<? extends proto.util.Util.StringDictItem> values) {
        if (result.attributes_.isEmpty()) {
          result.attributes_ = new java.util.ArrayList<proto.util.Util.StringDictItem>();
        }
        super.addAll(values, result.attributes_);
        return this;
      }
      public Builder clearAttributes() {
        result.attributes_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional bool enabled = 5;
      public boolean hasEnabled() {
        return result.hasEnabled();
      }
      public boolean getEnabled() {
        return result.getEnabled();
      }
      public Builder setEnabled(boolean value) {
        result.hasEnabled = true;
        result.enabled_ = value;
        return this;
      }
      public Builder clearEnabled() {
        result.hasEnabled = false;
        result.enabled_ = false;
        return this;
      }
      
      // optional bool ready = 6;
      public boolean hasReady() {
        return result.hasReady();
      }
      public boolean getReady() {
        return result.getReady();
      }
      public Builder setReady(boolean value) {
        result.hasReady = true;
        result.ready_ = value;
        return this;
      }
      public Builder clearReady() {
        result.hasReady = false;
        result.ready_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ArenaSlot)
    }
    
    static {
      defaultInstance = new ArenaSlot(true);
      proto.res.ResArena.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ArenaSlot)
  }
  
  public static final class ArenaList extends
      com.google.protobuf.GeneratedMessage {
    // Use ArenaList.newBuilder() to construct.
    private ArenaList() {
      initFields();
    }
    private ArenaList(boolean noInit) {}
    
    private static final ArenaList defaultInstance;
    public static ArenaList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArenaList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResArena.internal_static_ArenaList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResArena.internal_static_ArenaList_fieldAccessorTable;
    }
    
    // repeated .Arena arenas = 1;
    public static final int ARENAS_FIELD_NUMBER = 1;
    private java.util.List<proto.res.ResArena.Arena> arenas_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.res.ResArena.Arena> getArenasList() {
      return arenas_;
    }
    public int getArenasCount() { return arenas_.size(); }
    public proto.res.ResArena.Arena getArenas(int index) {
      return arenas_.get(index);
    }
    
    private void initFields() {
    }
    public static proto.res.ResArena.ArenaList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.ArenaList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResArena.ArenaList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResArena.ArenaList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResArena.ArenaList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResArena.ArenaList result;
      
      // Construct using proto.res.ResArena.ArenaList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResArena.ArenaList();
        return builder;
      }
      
      protected proto.res.ResArena.ArenaList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResArena.ArenaList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResArena.ArenaList.getDescriptor();
      }
      
      public proto.res.ResArena.ArenaList getDefaultInstanceForType() {
        return proto.res.ResArena.ArenaList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResArena.ArenaList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResArena.ArenaList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResArena.ArenaList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.arenas_ != java.util.Collections.EMPTY_LIST) {
          result.arenas_ =
            java.util.Collections.unmodifiableList(result.arenas_);
        }
        proto.res.ResArena.ArenaList returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .Arena arenas = 1;
      public java.util.List<proto.res.ResArena.Arena> getArenasList() {
        return java.util.Collections.unmodifiableList(result.arenas_);
      }
      public int getArenasCount() {
        return result.getArenasCount();
      }
      public proto.res.ResArena.Arena getArenas(int index) {
        return result.getArenas(index);
      }
      public Builder setArenas(int index, proto.res.ResArena.Arena value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.arenas_.set(index, value);
        return this;
      }
      public Builder setArenas(int index, proto.res.ResArena.Arena.Builder builderForValue) {
        result.arenas_.set(index, builderForValue.build());
        return this;
      }
      public Builder addArenas(proto.res.ResArena.Arena value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.arenas_.isEmpty()) {
          result.arenas_ = new java.util.ArrayList<proto.res.ResArena.Arena>();
        }
        result.arenas_.add(value);
        return this;
      }
      public Builder addArenas(proto.res.ResArena.Arena.Builder builderForValue) {
        if (result.arenas_.isEmpty()) {
          result.arenas_ = new java.util.ArrayList<proto.res.ResArena.Arena>();
        }
        result.arenas_.add(builderForValue.build());
        return this;
      }
      public Builder addAllArenas(
          java.lang.Iterable<? extends proto.res.ResArena.Arena> values) {
        if (result.arenas_.isEmpty()) {
          result.arenas_ = new java.util.ArrayList<proto.res.ResArena.Arena>();
        }
        super.addAll(values, result.arenas_);
        return this;
      }
      public Builder clearArenas() {
        result.arenas_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ArenaList)
    }
    
    static {
      defaultInstance = new ArenaList(true);
      proto.res.ResArena.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ArenaList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Arena_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Arena_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ArenaMini_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ArenaMini_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleForce_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BattleForce_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ArenaSlot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ArenaSlot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ArenaList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ArenaList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017res_arena.proto\032\016res_user.proto\032\016res_g" +
      "ame.proto\032\nutil.proto\032\016res_form.proto\"\363\003" +
      "\n\005Arena\022\n\n\002id\030\001 \001(\r\022!\n\013logicalGame\030\002 \001(\013" +
      "2\014.LogicalGame\022#\n\014physicalGame\030\003 \001(\0132\r.P" +
      "hysicalGame\022\025\n\007gameMap\030\004 \001(\0132\004.Map\022\016\n\006st" +
      "atus\030\005 \001(\t\022\033\n\007players\030\006 \003(\0132\n.ArenaSlot\022" +
      "#\n\nattributes\030\007 \003(\0132\017.StringDictItem\022\014\n\004" +
      "name\030\010 \001(\t\022\034\n\006forces\030\t \003(\0132\014.BattleForce" +
      "\0221\n\027userAttributeDefinition\030\n \001(\0132\020.Choi" +
      "ceFieldList\022\024\n\014private_flag\030\013 \001(\010\022\021\n\tcha",
      "tgroup\030\014 \001(\r\022\022\n\nmy_actions\030\r \003(\t\022\014\n\004mode" +
      "\030\016 \001(\t\022\014\n\004uuid\030\017 \001(\t\022\014\n\004type\030\024 \001(\t\022\017\n\007ma" +
      "ppath\030\020 \001(\t\022\020\n\010gamepath\030\021 \001(\t\022\016\n\006hostID\030" +
      "\022 \001(\r\022\016\n\006whoAmI\030\023 \001(\r\022\022\n\nevent_name\030\025 \001(" +
      "\t\022\020\n\010event_id\030\026 \001(\t\"\256\001\n\tArenaMini\022\n\n\002id\030" +
      "\001 \001(\r\022!\n\013logicalGame\030\002 \001(\0132\014.LogicalGame" +
      "\022#\n\014physicalGame\030\003 \001(\0132\r.PhysicalGame\022\025\n" +
      "\007gameMap\030\004 \001(\0132\004.Map\022\022\n\ntotalCount\030\005 \001(\r" +
      "\022\024\n\014currentCount\030\006 \001(\r\022\014\n\004mode\030\007 \001(\t\"\200\001\n" +
      "\013BattleForce\022\n\n\002id\030\001 \001(\r\022\r\n\005label\030\002 \001(\t\022",
      "\017\n\007partyID\030\n \001(\r\022\016\n\006status\030\003 \001(\t\022\020\n\010lead" +
      "erID\030\013 \001(\r\022#\n\nattributes\030\004 \003(\0132\017.StringD" +
      "ictItem\"\215\001\n\tArenaSlot\022\030\n\004user\030\001 \001(\0132\n.Us" +
      "erModel\022\020\n\010position\030\002 \001(\r\022\017\n\007forceID\030\003 \001" +
      "(\r\022#\n\nattributes\030\004 \003(\0132\017.StringDictItem\022" +
      "\017\n\007enabled\030\005 \001(\010\022\r\n\005ready\030\006 \001(\010\"#\n\tArena" +
      "List\022\026\n\006arenas\030\001 \003(\0132\006.ArenaB\r\n\tproto.re" +
      "sH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Arena_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Arena_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Arena_descriptor,
              new java.lang.String[] { "Id", "LogicalGame", "PhysicalGame", "GameMap", "Status", "Players", "Attributes", "Name", "Forces", "UserAttributeDefinition", "PrivateFlag", "Chatgroup", "MyActions", "Mode", "Uuid", "Type", "Mappath", "Gamepath", "HostID", "WhoAmI", "EventName", "EventId", },
              proto.res.ResArena.Arena.class,
              proto.res.ResArena.Arena.Builder.class);
          internal_static_ArenaMini_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ArenaMini_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ArenaMini_descriptor,
              new java.lang.String[] { "Id", "LogicalGame", "PhysicalGame", "GameMap", "TotalCount", "CurrentCount", "Mode", },
              proto.res.ResArena.ArenaMini.class,
              proto.res.ResArena.ArenaMini.Builder.class);
          internal_static_BattleForce_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_BattleForce_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BattleForce_descriptor,
              new java.lang.String[] { "Id", "Label", "PartyID", "Status", "LeaderID", "Attributes", },
              proto.res.ResArena.BattleForce.class,
              proto.res.ResArena.BattleForce.Builder.class);
          internal_static_ArenaSlot_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ArenaSlot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ArenaSlot_descriptor,
              new java.lang.String[] { "User", "Position", "ForceID", "Attributes", "Enabled", "Ready", },
              proto.res.ResArena.ArenaSlot.class,
              proto.res.ResArena.ArenaSlot.Builder.class);
          internal_static_ArenaList_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ArenaList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ArenaList_descriptor,
              new java.lang.String[] { "Arenas", },
              proto.res.ResArena.ArenaList.class,
              proto.res.ResArena.ArenaList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.response.ResUser.getDescriptor(),
          proto.response.ResGame.getDescriptor(),
          proto.util.Util.getDescriptor(),
          proto.res.ResForm.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
