// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: res_form.proto

package proto.res;

public final class ResForm {
  private ResForm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ChoiceFieldList extends
      com.google.protobuf.GeneratedMessage {
    // Use ChoiceFieldList.newBuilder() to construct.
    private ChoiceFieldList() {
      initFields();
    }
    private ChoiceFieldList(boolean noInit) {}
    
    private static final ChoiceFieldList defaultInstance;
    public static ChoiceFieldList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChoiceFieldList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResForm.internal_static_ChoiceFieldList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResForm.internal_static_ChoiceFieldList_fieldAccessorTable;
    }
    
    // repeated .ChoiceField choiceFields = 1;
    public static final int CHOICEFIELDS_FIELD_NUMBER = 1;
    private java.util.List<proto.res.ResForm.ChoiceField> choiceFields_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.res.ResForm.ChoiceField> getChoiceFieldsList() {
      return choiceFields_;
    }
    public int getChoiceFieldsCount() { return choiceFields_.size(); }
    public proto.res.ResForm.ChoiceField getChoiceFields(int index) {
      return choiceFields_.get(index);
    }
    
    // repeated .StringField stringFields = 2;
    public static final int STRINGFIELDS_FIELD_NUMBER = 2;
    private java.util.List<proto.res.ResForm.StringField> stringFields_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.res.ResForm.StringField> getStringFieldsList() {
      return stringFields_;
    }
    public int getStringFieldsCount() { return stringFields_.size(); }
    public proto.res.ResForm.StringField getStringFields(int index) {
      return stringFields_.get(index);
    }
    
    private void initFields() {
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.ChoiceFieldList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResForm.ChoiceFieldList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResForm.ChoiceFieldList result;
      
      // Construct using proto.res.ResForm.ChoiceFieldList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResForm.ChoiceFieldList();
        return builder;
      }
      
      protected proto.res.ResForm.ChoiceFieldList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResForm.ChoiceFieldList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResForm.ChoiceFieldList.getDescriptor();
      }
      
      public proto.res.ResForm.ChoiceFieldList getDefaultInstanceForType() {
        return proto.res.ResForm.ChoiceFieldList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResForm.ChoiceFieldList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResForm.ChoiceFieldList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResForm.ChoiceFieldList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.choiceFields_ != java.util.Collections.EMPTY_LIST) {
          result.choiceFields_ =
            java.util.Collections.unmodifiableList(result.choiceFields_);
        }
        if (result.stringFields_ != java.util.Collections.EMPTY_LIST) {
          result.stringFields_ =
            java.util.Collections.unmodifiableList(result.stringFields_);
        }
        proto.res.ResForm.ChoiceFieldList returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .ChoiceField choiceFields = 1;
      public java.util.List<proto.res.ResForm.ChoiceField> getChoiceFieldsList() {
        return java.util.Collections.unmodifiableList(result.choiceFields_);
      }
      public int getChoiceFieldsCount() {
        return result.getChoiceFieldsCount();
      }
      public proto.res.ResForm.ChoiceField getChoiceFields(int index) {
        return result.getChoiceFields(index);
      }
      public Builder setChoiceFields(int index, proto.res.ResForm.ChoiceField value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.choiceFields_.set(index, value);
        return this;
      }
      public Builder setChoiceFields(int index, proto.res.ResForm.ChoiceField.Builder builderForValue) {
        result.choiceFields_.set(index, builderForValue.build());
        return this;
      }
      public Builder addChoiceFields(proto.res.ResForm.ChoiceField value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.choiceFields_.isEmpty()) {
          result.choiceFields_ = new java.util.ArrayList<proto.res.ResForm.ChoiceField>();
        }
        result.choiceFields_.add(value);
        return this;
      }
      public Builder addChoiceFields(proto.res.ResForm.ChoiceField.Builder builderForValue) {
        if (result.choiceFields_.isEmpty()) {
          result.choiceFields_ = new java.util.ArrayList<proto.res.ResForm.ChoiceField>();
        }
        result.choiceFields_.add(builderForValue.build());
        return this;
      }
      public Builder addAllChoiceFields(
          java.lang.Iterable<? extends proto.res.ResForm.ChoiceField> values) {
        if (result.choiceFields_.isEmpty()) {
          result.choiceFields_ = new java.util.ArrayList<proto.res.ResForm.ChoiceField>();
        }
        super.addAll(values, result.choiceFields_);
        return this;
      }
      public Builder clearChoiceFields() {
        result.choiceFields_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .StringField stringFields = 2;
      public java.util.List<proto.res.ResForm.StringField> getStringFieldsList() {
        return java.util.Collections.unmodifiableList(result.stringFields_);
      }
      public int getStringFieldsCount() {
        return result.getStringFieldsCount();
      }
      public proto.res.ResForm.StringField getStringFields(int index) {
        return result.getStringFields(index);
      }
      public Builder setStringFields(int index, proto.res.ResForm.StringField value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.stringFields_.set(index, value);
        return this;
      }
      public Builder setStringFields(int index, proto.res.ResForm.StringField.Builder builderForValue) {
        result.stringFields_.set(index, builderForValue.build());
        return this;
      }
      public Builder addStringFields(proto.res.ResForm.StringField value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.stringFields_.isEmpty()) {
          result.stringFields_ = new java.util.ArrayList<proto.res.ResForm.StringField>();
        }
        result.stringFields_.add(value);
        return this;
      }
      public Builder addStringFields(proto.res.ResForm.StringField.Builder builderForValue) {
        if (result.stringFields_.isEmpty()) {
          result.stringFields_ = new java.util.ArrayList<proto.res.ResForm.StringField>();
        }
        result.stringFields_.add(builderForValue.build());
        return this;
      }
      public Builder addAllStringFields(
          java.lang.Iterable<? extends proto.res.ResForm.StringField> values) {
        if (result.stringFields_.isEmpty()) {
          result.stringFields_ = new java.util.ArrayList<proto.res.ResForm.StringField>();
        }
        super.addAll(values, result.stringFields_);
        return this;
      }
      public Builder clearStringFields() {
        result.stringFields_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ChoiceFieldList)
    }
    
    static {
      defaultInstance = new ChoiceFieldList(true);
      proto.res.ResForm.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChoiceFieldList)
  }
  
  public static final class ChoiceField extends
      com.google.protobuf.GeneratedMessage {
    // Use ChoiceField.newBuilder() to construct.
    private ChoiceField() {
      initFields();
    }
    private ChoiceField(boolean noInit) {}
    
    private static final ChoiceField defaultInstance;
    public static ChoiceField getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChoiceField getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResForm.internal_static_ChoiceField_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResForm.internal_static_ChoiceField_fieldAccessorTable;
    }
    
    // optional bool isRequired = 1;
    public static final int ISREQUIRED_FIELD_NUMBER = 1;
    private boolean hasIsRequired;
    private boolean isRequired_ = false;
    public boolean hasIsRequired() { return hasIsRequired; }
    public boolean getIsRequired() { return isRequired_; }
    
    // optional string label = 2;
    public static final int LABEL_FIELD_NUMBER = 2;
    private boolean hasLabel;
    private java.lang.String label_ = "";
    public boolean hasLabel() { return hasLabel; }
    public java.lang.String getLabel() { return label_; }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .ChoiceFieldOption options = 4;
    public static final int OPTIONS_FIELD_NUMBER = 4;
    private java.util.List<proto.res.ResForm.ChoiceFieldOption> options_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.res.ResForm.ChoiceFieldOption> getOptionsList() {
      return options_;
    }
    public int getOptionsCount() { return options_.size(); }
    public proto.res.ResForm.ChoiceFieldOption getOptions(int index) {
      return options_.get(index);
    }
    
    private void initFields() {
    }
    public static proto.res.ResForm.ChoiceField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.ChoiceField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.ChoiceField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.ChoiceField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResForm.ChoiceField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResForm.ChoiceField result;
      
      // Construct using proto.res.ResForm.ChoiceField.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResForm.ChoiceField();
        return builder;
      }
      
      protected proto.res.ResForm.ChoiceField internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResForm.ChoiceField();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResForm.ChoiceField.getDescriptor();
      }
      
      public proto.res.ResForm.ChoiceField getDefaultInstanceForType() {
        return proto.res.ResForm.ChoiceField.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResForm.ChoiceField build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResForm.ChoiceField buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResForm.ChoiceField buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.options_ != java.util.Collections.EMPTY_LIST) {
          result.options_ =
            java.util.Collections.unmodifiableList(result.options_);
        }
        proto.res.ResForm.ChoiceField returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional bool isRequired = 1;
      public boolean hasIsRequired() {
        return result.hasIsRequired();
      }
      public boolean getIsRequired() {
        return result.getIsRequired();
      }
      public Builder setIsRequired(boolean value) {
        result.hasIsRequired = true;
        result.isRequired_ = value;
        return this;
      }
      public Builder clearIsRequired() {
        result.hasIsRequired = false;
        result.isRequired_ = false;
        return this;
      }
      
      // optional string label = 2;
      public boolean hasLabel() {
        return result.hasLabel();
      }
      public java.lang.String getLabel() {
        return result.getLabel();
      }
      public Builder setLabel(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLabel = true;
        result.label_ = value;
        return this;
      }
      public Builder clearLabel() {
        result.hasLabel = false;
        result.label_ = getDefaultInstance().getLabel();
        return this;
      }
      
      // optional string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .ChoiceFieldOption options = 4;
      public java.util.List<proto.res.ResForm.ChoiceFieldOption> getOptionsList() {
        return java.util.Collections.unmodifiableList(result.options_);
      }
      public int getOptionsCount() {
        return result.getOptionsCount();
      }
      public proto.res.ResForm.ChoiceFieldOption getOptions(int index) {
        return result.getOptions(index);
      }
      public Builder setOptions(int index, proto.res.ResForm.ChoiceFieldOption value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.options_.set(index, value);
        return this;
      }
      public Builder setOptions(int index, proto.res.ResForm.ChoiceFieldOption.Builder builderForValue) {
        result.options_.set(index, builderForValue.build());
        return this;
      }
      public Builder addOptions(proto.res.ResForm.ChoiceFieldOption value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.options_.isEmpty()) {
          result.options_ = new java.util.ArrayList<proto.res.ResForm.ChoiceFieldOption>();
        }
        result.options_.add(value);
        return this;
      }
      public Builder addOptions(proto.res.ResForm.ChoiceFieldOption.Builder builderForValue) {
        if (result.options_.isEmpty()) {
          result.options_ = new java.util.ArrayList<proto.res.ResForm.ChoiceFieldOption>();
        }
        result.options_.add(builderForValue.build());
        return this;
      }
      public Builder addAllOptions(
          java.lang.Iterable<? extends proto.res.ResForm.ChoiceFieldOption> values) {
        if (result.options_.isEmpty()) {
          result.options_ = new java.util.ArrayList<proto.res.ResForm.ChoiceFieldOption>();
        }
        super.addAll(values, result.options_);
        return this;
      }
      public Builder clearOptions() {
        result.options_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ChoiceField)
    }
    
    static {
      defaultInstance = new ChoiceField(true);
      proto.res.ResForm.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChoiceField)
  }
  
  public static final class ChoiceFieldOption extends
      com.google.protobuf.GeneratedMessage {
    // Use ChoiceFieldOption.newBuilder() to construct.
    private ChoiceFieldOption() {
      initFields();
    }
    private ChoiceFieldOption(boolean noInit) {}
    
    private static final ChoiceFieldOption defaultInstance;
    public static ChoiceFieldOption getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChoiceFieldOption getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResForm.internal_static_ChoiceFieldOption_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResForm.internal_static_ChoiceFieldOption_fieldAccessorTable;
    }
    
    // optional string label = 1;
    public static final int LABEL_FIELD_NUMBER = 1;
    private boolean hasLabel;
    private java.lang.String label_ = "";
    public boolean hasLabel() { return hasLabel; }
    public java.lang.String getLabel() { return label_; }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    private void initFields() {
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.ChoiceFieldOption parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.ChoiceFieldOption parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResForm.ChoiceFieldOption prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResForm.ChoiceFieldOption result;
      
      // Construct using proto.res.ResForm.ChoiceFieldOption.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResForm.ChoiceFieldOption();
        return builder;
      }
      
      protected proto.res.ResForm.ChoiceFieldOption internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResForm.ChoiceFieldOption();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResForm.ChoiceFieldOption.getDescriptor();
      }
      
      public proto.res.ResForm.ChoiceFieldOption getDefaultInstanceForType() {
        return proto.res.ResForm.ChoiceFieldOption.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResForm.ChoiceFieldOption build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResForm.ChoiceFieldOption buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResForm.ChoiceFieldOption buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.res.ResForm.ChoiceFieldOption returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string label = 1;
      public boolean hasLabel() {
        return result.hasLabel();
      }
      public java.lang.String getLabel() {
        return result.getLabel();
      }
      public Builder setLabel(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLabel = true;
        result.label_ = value;
        return this;
      }
      public Builder clearLabel() {
        result.hasLabel = false;
        result.label_ = getDefaultInstance().getLabel();
        return this;
      }
      
      // optional string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = getDefaultInstance().getValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ChoiceFieldOption)
    }
    
    static {
      defaultInstance = new ChoiceFieldOption(true);
      proto.res.ResForm.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChoiceFieldOption)
  }
  
  public static final class StringField extends
      com.google.protobuf.GeneratedMessage {
    // Use StringField.newBuilder() to construct.
    private StringField() {
      initFields();
    }
    private StringField(boolean noInit) {}
    
    private static final StringField defaultInstance;
    public static StringField getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringField getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.res.ResForm.internal_static_StringField_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.res.ResForm.internal_static_StringField_fieldAccessorTable;
    }
    
    // optional bool isRequired = 1;
    public static final int ISREQUIRED_FIELD_NUMBER = 1;
    private boolean hasIsRequired;
    private boolean isRequired_ = false;
    public boolean hasIsRequired() { return hasIsRequired; }
    public boolean getIsRequired() { return isRequired_; }
    
    // optional string label = 2;
    public static final int LABEL_FIELD_NUMBER = 2;
    private boolean hasLabel;
    private java.lang.String label_ = "";
    public boolean hasLabel() { return hasLabel; }
    public java.lang.String getLabel() { return label_; }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public static proto.res.ResForm.StringField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.StringField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.StringField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.res.ResForm.StringField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.StringField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.StringField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.res.ResForm.StringField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.StringField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.res.ResForm.StringField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.res.ResForm.StringField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.res.ResForm.StringField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.res.ResForm.StringField result;
      
      // Construct using proto.res.ResForm.StringField.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.res.ResForm.StringField();
        return builder;
      }
      
      protected proto.res.ResForm.StringField internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.res.ResForm.StringField();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.res.ResForm.StringField.getDescriptor();
      }
      
      public proto.res.ResForm.StringField getDefaultInstanceForType() {
        return proto.res.ResForm.StringField.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.res.ResForm.StringField build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.res.ResForm.StringField buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.res.ResForm.StringField buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.res.ResForm.StringField returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional bool isRequired = 1;
      public boolean hasIsRequired() {
        return result.hasIsRequired();
      }
      public boolean getIsRequired() {
        return result.getIsRequired();
      }
      public Builder setIsRequired(boolean value) {
        result.hasIsRequired = true;
        result.isRequired_ = value;
        return this;
      }
      public Builder clearIsRequired() {
        result.hasIsRequired = false;
        result.isRequired_ = false;
        return this;
      }
      
      // optional string label = 2;
      public boolean hasLabel() {
        return result.hasLabel();
      }
      public java.lang.String getLabel() {
        return result.getLabel();
      }
      public Builder setLabel(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLabel = true;
        result.label_ = value;
        return this;
      }
      public Builder clearLabel() {
        result.hasLabel = false;
        result.label_ = getDefaultInstance().getLabel();
        return this;
      }
      
      // optional string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:StringField)
    }
    
    static {
      defaultInstance = new StringField(true);
      proto.res.ResForm.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:StringField)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChoiceFieldList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChoiceFieldList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChoiceField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChoiceField_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChoiceFieldOption_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChoiceFieldOption_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StringField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringField_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016res_form.proto\"Y\n\017ChoiceFieldList\022\"\n\014c" +
      "hoiceFields\030\001 \003(\0132\014.ChoiceField\022\"\n\014strin" +
      "gFields\030\002 \003(\0132\014.StringField\"c\n\013ChoiceFie" +
      "ld\022\022\n\nisRequired\030\001 \001(\010\022\r\n\005label\030\002 \001(\t\022\014\n" +
      "\004name\030\003 \001(\t\022#\n\007options\030\004 \003(\0132\022.ChoiceFie" +
      "ldOption\"1\n\021ChoiceFieldOption\022\r\n\005label\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t\">\n\013StringField\022\022\n\nis" +
      "Required\030\001 \001(\010\022\r\n\005label\030\002 \001(\t\022\014\n\004name\030\003 " +
      "\001(\tB\r\n\tproto.resH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ChoiceFieldList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ChoiceFieldList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChoiceFieldList_descriptor,
              new java.lang.String[] { "ChoiceFields", "StringFields", },
              proto.res.ResForm.ChoiceFieldList.class,
              proto.res.ResForm.ChoiceFieldList.Builder.class);
          internal_static_ChoiceField_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ChoiceField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChoiceField_descriptor,
              new java.lang.String[] { "IsRequired", "Label", "Name", "Options", },
              proto.res.ResForm.ChoiceField.class,
              proto.res.ResForm.ChoiceField.Builder.class);
          internal_static_ChoiceFieldOption_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ChoiceFieldOption_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChoiceFieldOption_descriptor,
              new java.lang.String[] { "Label", "Value", },
              proto.res.ResForm.ChoiceFieldOption.class,
              proto.res.ResForm.ChoiceFieldOption.Builder.class);
          internal_static_StringField_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_StringField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StringField_descriptor,
              new java.lang.String[] { "IsRequired", "Label", "Name", },
              proto.res.ResForm.StringField.class,
              proto.res.ResForm.StringField.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
