// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.gamemate.app.domain.event.rts;

import java.lang.Iterable;
import java.lang.String;

privileged aspect PlayerInfoChecker_Roo_JavaBean {
    
    public Iterable<String> PlayerInfoChecker.getRequiredFields() {
        return this.requiredFields;
    }
    
}
