// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: res_activity.proto

package proto.response;

public final class ResActivity {
  private ResActivity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ActivityGetResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ActivityGetResponse.newBuilder() to construct.
    private ActivityGetResponse() {
      initFields();
    }
    private ActivityGetResponse(boolean noInit) {}
    
    private static final ActivityGetResponse defaultInstance;
    public static ActivityGetResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ActivityGetResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.response.ResActivity.internal_static_ActivityGetResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.response.ResActivity.internal_static_ActivityGetResponse_fieldAccessorTable;
    }
    
    // optional uint32 id = 4;
    public static final int ID_FIELD_NUMBER = 4;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    // optional string logo = 2;
    public static final int LOGO_FIELD_NUMBER = 2;
    private boolean hasLogo;
    private java.lang.String logo_ = "";
    public boolean hasLogo() { return hasLogo; }
    public java.lang.String getLogo() { return logo_; }
    
    // optional uint32 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private boolean hasTimestamp;
    private int timestamp_ = 0;
    public boolean hasTimestamp() { return hasTimestamp; }
    public int getTimestamp() { return timestamp_; }
    
    private void initFields() {
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResActivity.ActivityGetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResActivity.ActivityGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.response.ResActivity.ActivityGetResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.response.ResActivity.ActivityGetResponse result;
      
      // Construct using proto.response.ResActivity.ActivityGetResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.response.ResActivity.ActivityGetResponse();
        return builder;
      }
      
      protected proto.response.ResActivity.ActivityGetResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.response.ResActivity.ActivityGetResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.response.ResActivity.ActivityGetResponse.getDescriptor();
      }
      
      public proto.response.ResActivity.ActivityGetResponse getDefaultInstanceForType() {
        return proto.response.ResActivity.ActivityGetResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.response.ResActivity.ActivityGetResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.response.ResActivity.ActivityGetResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.response.ResActivity.ActivityGetResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.response.ResActivity.ActivityGetResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 id = 4;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string text = 1;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
      
      // optional string logo = 2;
      public boolean hasLogo() {
        return result.hasLogo();
      }
      public java.lang.String getLogo() {
        return result.getLogo();
      }
      public Builder setLogo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLogo = true;
        result.logo_ = value;
        return this;
      }
      public Builder clearLogo() {
        result.hasLogo = false;
        result.logo_ = getDefaultInstance().getLogo();
        return this;
      }
      
      // optional uint32 timestamp = 3;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public int getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(int value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ActivityGetResponse)
    }
    
    static {
      defaultInstance = new ActivityGetResponse(true);
      proto.response.ResActivity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ActivityGetResponse)
  }
  
  public static final class ActivityListResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ActivityListResponse.newBuilder() to construct.
    private ActivityListResponse() {
      initFields();
    }
    private ActivityListResponse(boolean noInit) {}
    
    private static final ActivityListResponse defaultInstance;
    public static ActivityListResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ActivityListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.response.ResActivity.internal_static_ActivityListResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.response.ResActivity.internal_static_ActivityListResponse_fieldAccessorTable;
    }
    
    // repeated .ActivityGetResponse activities = 1;
    public static final int ACTIVITIES_FIELD_NUMBER = 1;
    private java.util.List<proto.response.ResActivity.ActivityGetResponse> activities_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.response.ResActivity.ActivityGetResponse> getActivitiesList() {
      return activities_;
    }
    public int getActivitiesCount() { return activities_.size(); }
    public proto.response.ResActivity.ActivityGetResponse getActivities(int index) {
      return activities_.get(index);
    }
    
    // optional .ListParams params = 2;
    public static final int PARAMS_FIELD_NUMBER = 2;
    private boolean hasParams;
    private proto.response.ResListbase.ListParams params_;
    public boolean hasParams() { return hasParams; }
    public proto.response.ResListbase.ListParams getParams() { return params_; }
    
    private void initFields() {
      params_ = proto.response.ResListbase.ListParams.getDefaultInstance();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResActivity.ActivityListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResActivity.ActivityListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.response.ResActivity.ActivityListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.response.ResActivity.ActivityListResponse result;
      
      // Construct using proto.response.ResActivity.ActivityListResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.response.ResActivity.ActivityListResponse();
        return builder;
      }
      
      protected proto.response.ResActivity.ActivityListResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.response.ResActivity.ActivityListResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.response.ResActivity.ActivityListResponse.getDescriptor();
      }
      
      public proto.response.ResActivity.ActivityListResponse getDefaultInstanceForType() {
        return proto.response.ResActivity.ActivityListResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.response.ResActivity.ActivityListResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.response.ResActivity.ActivityListResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.response.ResActivity.ActivityListResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.activities_ != java.util.Collections.EMPTY_LIST) {
          result.activities_ =
            java.util.Collections.unmodifiableList(result.activities_);
        }
        proto.response.ResActivity.ActivityListResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .ActivityGetResponse activities = 1;
      public java.util.List<proto.response.ResActivity.ActivityGetResponse> getActivitiesList() {
        return java.util.Collections.unmodifiableList(result.activities_);
      }
      public int getActivitiesCount() {
        return result.getActivitiesCount();
      }
      public proto.response.ResActivity.ActivityGetResponse getActivities(int index) {
        return result.getActivities(index);
      }
      public Builder setActivities(int index, proto.response.ResActivity.ActivityGetResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.activities_.set(index, value);
        return this;
      }
      public Builder setActivities(int index, proto.response.ResActivity.ActivityGetResponse.Builder builderForValue) {
        result.activities_.set(index, builderForValue.build());
        return this;
      }
      public Builder addActivities(proto.response.ResActivity.ActivityGetResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.activities_.isEmpty()) {
          result.activities_ = new java.util.ArrayList<proto.response.ResActivity.ActivityGetResponse>();
        }
        result.activities_.add(value);
        return this;
      }
      public Builder addActivities(proto.response.ResActivity.ActivityGetResponse.Builder builderForValue) {
        if (result.activities_.isEmpty()) {
          result.activities_ = new java.util.ArrayList<proto.response.ResActivity.ActivityGetResponse>();
        }
        result.activities_.add(builderForValue.build());
        return this;
      }
      public Builder addAllActivities(
          java.lang.Iterable<? extends proto.response.ResActivity.ActivityGetResponse> values) {
        if (result.activities_.isEmpty()) {
          result.activities_ = new java.util.ArrayList<proto.response.ResActivity.ActivityGetResponse>();
        }
        super.addAll(values, result.activities_);
        return this;
      }
      public Builder clearActivities() {
        result.activities_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .ListParams params = 2;
      public boolean hasParams() {
        return result.hasParams();
      }
      public proto.response.ResListbase.ListParams getParams() {
        return result.getParams();
      }
      public Builder setParams(proto.response.ResListbase.ListParams value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasParams = true;
        result.params_ = value;
        return this;
      }
      public Builder setParams(proto.response.ResListbase.ListParams.Builder builderForValue) {
        result.hasParams = true;
        result.params_ = builderForValue.build();
        return this;
      }
      public Builder mergeParams(proto.response.ResListbase.ListParams value) {
        if (result.hasParams() &&
            result.params_ != proto.response.ResListbase.ListParams.getDefaultInstance()) {
          result.params_ =
            proto.response.ResListbase.ListParams.newBuilder(result.params_).mergeFrom(value).buildPartial();
        } else {
          result.params_ = value;
        }
        result.hasParams = true;
        return this;
      }
      public Builder clearParams() {
        result.hasParams = false;
        result.params_ = proto.response.ResListbase.ListParams.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ActivityListResponse)
    }
    
    static {
      defaultInstance = new ActivityListResponse(true);
      proto.response.ResActivity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ActivityListResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivityGetResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActivityGetResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivityListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActivityListResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022res_activity.proto\032\022res_listbase.proto" +
      "\"P\n\023ActivityGetResponse\022\n\n\002id\030\004 \001(\r\022\014\n\004t" +
      "ext\030\001 \001(\t\022\014\n\004logo\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001" +
      "(\r\"]\n\024ActivityListResponse\022(\n\nactivities" +
      "\030\001 \003(\0132\024.ActivityGetResponse\022\033\n\006params\030\002" +
      " \001(\0132\013.ListParamsB\022\n\016proto.responseH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ActivityGetResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ActivityGetResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ActivityGetResponse_descriptor,
              new java.lang.String[] { "Id", "Text", "Logo", "Timestamp", },
              proto.response.ResActivity.ActivityGetResponse.class,
              proto.response.ResActivity.ActivityGetResponse.Builder.class);
          internal_static_ActivityListResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ActivityListResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ActivityListResponse_descriptor,
              new java.lang.String[] { "Activities", "Params", },
              proto.response.ResActivity.ActivityListResponse.class,
              proto.response.ResActivity.ActivityListResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.response.ResListbase.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
