// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: res_chatgroup.proto

package proto.response;

public final class ResChatgroup {
  private ResChatgroup() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ChatGroupModel extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatGroupModel.newBuilder() to construct.
    private ChatGroupModel() {
      initFields();
    }
    private ChatGroupModel(boolean noInit) {}
    
    private static final ChatGroupModel defaultInstance;
    public static ChatGroupModel getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatGroupModel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.response.ResChatgroup.internal_static_ChatGroupModel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.response.ResChatgroup.internal_static_ChatGroupModel_fieldAccessorTable;
    }
    
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // repeated .UserModel users = 2;
    public static final int USERS_FIELD_NUMBER = 2;
    private java.util.List<proto.response.ResUser.UserModel> users_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.response.ResUser.UserModel> getUsersList() {
      return users_;
    }
    public int getUsersCount() { return users_.size(); }
    public proto.response.ResUser.UserModel getUsers(int index) {
      return users_.get(index);
    }
    
    private void initFields() {
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.response.ResChatgroup.ChatGroupModel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.response.ResChatgroup.ChatGroupModel result;
      
      // Construct using proto.response.ResChatgroup.ChatGroupModel.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.response.ResChatgroup.ChatGroupModel();
        return builder;
      }
      
      protected proto.response.ResChatgroup.ChatGroupModel internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.response.ResChatgroup.ChatGroupModel();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.response.ResChatgroup.ChatGroupModel.getDescriptor();
      }
      
      public proto.response.ResChatgroup.ChatGroupModel getDefaultInstanceForType() {
        return proto.response.ResChatgroup.ChatGroupModel.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.response.ResChatgroup.ChatGroupModel build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.response.ResChatgroup.ChatGroupModel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.response.ResChatgroup.ChatGroupModel buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.users_ != java.util.Collections.EMPTY_LIST) {
          result.users_ =
            java.util.Collections.unmodifiableList(result.users_);
        }
        proto.response.ResChatgroup.ChatGroupModel returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required uint32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // repeated .UserModel users = 2;
      public java.util.List<proto.response.ResUser.UserModel> getUsersList() {
        return java.util.Collections.unmodifiableList(result.users_);
      }
      public int getUsersCount() {
        return result.getUsersCount();
      }
      public proto.response.ResUser.UserModel getUsers(int index) {
        return result.getUsers(index);
      }
      public Builder setUsers(int index, proto.response.ResUser.UserModel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.users_.set(index, value);
        return this;
      }
      public Builder setUsers(int index, proto.response.ResUser.UserModel.Builder builderForValue) {
        result.users_.set(index, builderForValue.build());
        return this;
      }
      public Builder addUsers(proto.response.ResUser.UserModel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.users_.isEmpty()) {
          result.users_ = new java.util.ArrayList<proto.response.ResUser.UserModel>();
        }
        result.users_.add(value);
        return this;
      }
      public Builder addUsers(proto.response.ResUser.UserModel.Builder builderForValue) {
        if (result.users_.isEmpty()) {
          result.users_ = new java.util.ArrayList<proto.response.ResUser.UserModel>();
        }
        result.users_.add(builderForValue.build());
        return this;
      }
      public Builder addAllUsers(
          java.lang.Iterable<? extends proto.response.ResUser.UserModel> values) {
        if (result.users_.isEmpty()) {
          result.users_ = new java.util.ArrayList<proto.response.ResUser.UserModel>();
        }
        super.addAll(values, result.users_);
        return this;
      }
      public Builder clearUsers() {
        result.users_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ChatGroupModel)
    }
    
    static {
      defaultInstance = new ChatGroupModel(true);
      proto.response.ResChatgroup.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChatGroupModel)
  }
  
  public static final class ChatGroupList extends
      com.google.protobuf.GeneratedMessage {
    // Use ChatGroupList.newBuilder() to construct.
    private ChatGroupList() {
      initFields();
    }
    private ChatGroupList(boolean noInit) {}
    
    private static final ChatGroupList defaultInstance;
    public static ChatGroupList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChatGroupList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.response.ResChatgroup.internal_static_ChatGroupList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.response.ResChatgroup.internal_static_ChatGroupList_fieldAccessorTable;
    }
    
    // repeated .ChatGroupModel chatGroups = 1;
    public static final int CHATGROUPS_FIELD_NUMBER = 1;
    private java.util.List<proto.response.ResChatgroup.ChatGroupModel> chatGroups_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.response.ResChatgroup.ChatGroupModel> getChatGroupsList() {
      return chatGroups_;
    }
    public int getChatGroupsCount() { return chatGroups_.size(); }
    public proto.response.ResChatgroup.ChatGroupModel getChatGroups(int index) {
      return chatGroups_.get(index);
    }
    
    // optional uint32 placeholder = 15;
    public static final int PLACEHOLDER_FIELD_NUMBER = 15;
    private boolean hasPlaceholder;
    private int placeholder_ = 0;
    public boolean hasPlaceholder() { return hasPlaceholder; }
    public int getPlaceholder() { return placeholder_; }
    
    private void initFields() {
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResChatgroup.ChatGroupList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.response.ResChatgroup.ChatGroupList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.response.ResChatgroup.ChatGroupList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.response.ResChatgroup.ChatGroupList result;
      
      // Construct using proto.response.ResChatgroup.ChatGroupList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.response.ResChatgroup.ChatGroupList();
        return builder;
      }
      
      protected proto.response.ResChatgroup.ChatGroupList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.response.ResChatgroup.ChatGroupList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.response.ResChatgroup.ChatGroupList.getDescriptor();
      }
      
      public proto.response.ResChatgroup.ChatGroupList getDefaultInstanceForType() {
        return proto.response.ResChatgroup.ChatGroupList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.response.ResChatgroup.ChatGroupList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.response.ResChatgroup.ChatGroupList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.response.ResChatgroup.ChatGroupList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.chatGroups_ != java.util.Collections.EMPTY_LIST) {
          result.chatGroups_ =
            java.util.Collections.unmodifiableList(result.chatGroups_);
        }
        proto.response.ResChatgroup.ChatGroupList returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .ChatGroupModel chatGroups = 1;
      public java.util.List<proto.response.ResChatgroup.ChatGroupModel> getChatGroupsList() {
        return java.util.Collections.unmodifiableList(result.chatGroups_);
      }
      public int getChatGroupsCount() {
        return result.getChatGroupsCount();
      }
      public proto.response.ResChatgroup.ChatGroupModel getChatGroups(int index) {
        return result.getChatGroups(index);
      }
      public Builder setChatGroups(int index, proto.response.ResChatgroup.ChatGroupModel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.chatGroups_.set(index, value);
        return this;
      }
      public Builder setChatGroups(int index, proto.response.ResChatgroup.ChatGroupModel.Builder builderForValue) {
        result.chatGroups_.set(index, builderForValue.build());
        return this;
      }
      public Builder addChatGroups(proto.response.ResChatgroup.ChatGroupModel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.chatGroups_.isEmpty()) {
          result.chatGroups_ = new java.util.ArrayList<proto.response.ResChatgroup.ChatGroupModel>();
        }
        result.chatGroups_.add(value);
        return this;
      }
      public Builder addChatGroups(proto.response.ResChatgroup.ChatGroupModel.Builder builderForValue) {
        if (result.chatGroups_.isEmpty()) {
          result.chatGroups_ = new java.util.ArrayList<proto.response.ResChatgroup.ChatGroupModel>();
        }
        result.chatGroups_.add(builderForValue.build());
        return this;
      }
      public Builder addAllChatGroups(
          java.lang.Iterable<? extends proto.response.ResChatgroup.ChatGroupModel> values) {
        if (result.chatGroups_.isEmpty()) {
          result.chatGroups_ = new java.util.ArrayList<proto.response.ResChatgroup.ChatGroupModel>();
        }
        super.addAll(values, result.chatGroups_);
        return this;
      }
      public Builder clearChatGroups() {
        result.chatGroups_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 placeholder = 15;
      public boolean hasPlaceholder() {
        return result.hasPlaceholder();
      }
      public int getPlaceholder() {
        return result.getPlaceholder();
      }
      public Builder setPlaceholder(int value) {
        result.hasPlaceholder = true;
        result.placeholder_ = value;
        return this;
      }
      public Builder clearPlaceholder() {
        result.hasPlaceholder = false;
        result.placeholder_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ChatGroupList)
    }
    
    static {
      defaultInstance = new ChatGroupList(true);
      proto.response.ResChatgroup.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ChatGroupList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatGroupModel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChatGroupModel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatGroupList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChatGroupList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023res_chatgroup.proto\032\016res_user.proto\"7\n" +
      "\016ChatGroupModel\022\n\n\002id\030\001 \002(\r\022\031\n\005users\030\002 \003" +
      "(\0132\n.UserModel\"I\n\rChatGroupList\022#\n\nchatG" +
      "roups\030\001 \003(\0132\017.ChatGroupModel\022\023\n\013placehol" +
      "der\030\017 \001(\rB\022\n\016proto.responseH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ChatGroupModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ChatGroupModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChatGroupModel_descriptor,
              new java.lang.String[] { "Id", "Users", },
              proto.response.ResChatgroup.ChatGroupModel.class,
              proto.response.ResChatgroup.ChatGroupModel.Builder.class);
          internal_static_ChatGroupList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ChatGroupList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ChatGroupList_descriptor,
              new java.lang.String[] { "ChatGroups", "Placeholder", },
              proto.response.ResChatgroup.ChatGroupList.class,
              proto.response.ResChatgroup.ChatGroupList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.response.ResUser.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
