// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_chat.proto

package proto.msg;

public final class MsgChat {
  private MsgChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GroupChat extends
      com.google.protobuf.GeneratedMessage {
    // Use GroupChat.newBuilder() to construct.
    private GroupChat() {
      initFields();
    }
    private GroupChat(boolean noInit) {}
    
    private static final GroupChat defaultInstance;
    public static GroupChat getDefaultInstance() {
      return defaultInstance;
    }
    
    public GroupChat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgChat.internal_static_GroupChat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgChat.internal_static_GroupChat_fieldAccessorTable;
    }
    
    // optional uint32 groupID = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private boolean hasGroupID;
    private int groupID_ = 0;
    public boolean hasGroupID() { return hasGroupID; }
    public int getGroupID() { return groupID_; }
    
    // optional uint32 senderID = 2;
    public static final int SENDERID_FIELD_NUMBER = 2;
    private boolean hasSenderID;
    private int senderID_ = 0;
    public boolean hasSenderID() { return hasSenderID; }
    public int getSenderID() { return senderID_; }
    
    // optional uint32 receiverID = 3;
    public static final int RECEIVERID_FIELD_NUMBER = 3;
    private boolean hasReceiverID;
    private int receiverID_ = 0;
    public boolean hasReceiverID() { return hasReceiverID; }
    public int getReceiverID() { return receiverID_; }
    
    // optional string content = 4;
    public static final int CONTENT_FIELD_NUMBER = 4;
    private boolean hasContent;
    private java.lang.String content_ = "";
    public boolean hasContent() { return hasContent; }
    public java.lang.String getContent() { return content_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgChat.GroupChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgChat.GroupChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgChat.GroupChat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgChat.GroupChat result;
      
      // Construct using proto.msg.MsgChat.GroupChat.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgChat.GroupChat();
        return builder;
      }
      
      protected proto.msg.MsgChat.GroupChat internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgChat.GroupChat();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgChat.GroupChat.getDescriptor();
      }
      
      public proto.msg.MsgChat.GroupChat getDefaultInstanceForType() {
        return proto.msg.MsgChat.GroupChat.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgChat.GroupChat build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgChat.GroupChat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgChat.GroupChat buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgChat.GroupChat returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 groupID = 1;
      public boolean hasGroupID() {
        return result.hasGroupID();
      }
      public int getGroupID() {
        return result.getGroupID();
      }
      public Builder setGroupID(int value) {
        result.hasGroupID = true;
        result.groupID_ = value;
        return this;
      }
      public Builder clearGroupID() {
        result.hasGroupID = false;
        result.groupID_ = 0;
        return this;
      }
      
      // optional uint32 senderID = 2;
      public boolean hasSenderID() {
        return result.hasSenderID();
      }
      public int getSenderID() {
        return result.getSenderID();
      }
      public Builder setSenderID(int value) {
        result.hasSenderID = true;
        result.senderID_ = value;
        return this;
      }
      public Builder clearSenderID() {
        result.hasSenderID = false;
        result.senderID_ = 0;
        return this;
      }
      
      // optional uint32 receiverID = 3;
      public boolean hasReceiverID() {
        return result.hasReceiverID();
      }
      public int getReceiverID() {
        return result.getReceiverID();
      }
      public Builder setReceiverID(int value) {
        result.hasReceiverID = true;
        result.receiverID_ = value;
        return this;
      }
      public Builder clearReceiverID() {
        result.hasReceiverID = false;
        result.receiverID_ = 0;
        return this;
      }
      
      // optional string content = 4;
      public boolean hasContent() {
        return result.hasContent();
      }
      public java.lang.String getContent() {
        return result.getContent();
      }
      public Builder setContent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContent = true;
        result.content_ = value;
        return this;
      }
      public Builder clearContent() {
        result.hasContent = false;
        result.content_ = getDefaultInstance().getContent();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:GroupChat)
    }
    
    static {
      defaultInstance = new GroupChat(true);
      proto.msg.MsgChat.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GroupChat)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GroupChat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GroupChat_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016msg_chat.proto\"S\n\tGroupChat\022\017\n\007groupID" +
      "\030\001 \001(\r\022\020\n\010senderID\030\002 \001(\r\022\022\n\nreceiverID\030\003" +
      " \001(\r\022\017\n\007content\030\004 \001(\tB\r\n\tproto.msgH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GroupChat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GroupChat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GroupChat_descriptor,
              new java.lang.String[] { "GroupID", "SenderID", "ReceiverID", "Content", },
              proto.msg.MsgChat.GroupChat.class,
              proto.msg.MsgChat.GroupChat.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
