// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_party.proto

package proto.msg;

public final class MsgParty {
  private MsgParty() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PartyJoined extends
      com.google.protobuf.GeneratedMessage {
    // Use PartyJoined.newBuilder() to construct.
    private PartyJoined() {
      initFields();
    }
    private PartyJoined(boolean noInit) {}
    
    private static final PartyJoined defaultInstance;
    public static PartyJoined getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartyJoined getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_PartyJoined_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_PartyJoined_fieldAccessorTable;
    }
    
    // optional .PartyModel party = 2;
    public static final int PARTY_FIELD_NUMBER = 2;
    private boolean hasParty;
    private proto.response.ResParty.PartyModel party_;
    public boolean hasParty() { return hasParty; }
    public proto.response.ResParty.PartyModel getParty() { return party_; }
    
    private void initFields() {
      party_ = proto.response.ResParty.PartyModel.getDefaultInstance();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyJoined parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyJoined parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.PartyJoined prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.PartyJoined result;
      
      // Construct using proto.msg.MsgParty.PartyJoined.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.PartyJoined();
        return builder;
      }
      
      protected proto.msg.MsgParty.PartyJoined internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.PartyJoined();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.PartyJoined.getDescriptor();
      }
      
      public proto.msg.MsgParty.PartyJoined getDefaultInstanceForType() {
        return proto.msg.MsgParty.PartyJoined.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.PartyJoined build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.PartyJoined buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.PartyJoined buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.PartyJoined returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional .PartyModel party = 2;
      public boolean hasParty() {
        return result.hasParty();
      }
      public proto.response.ResParty.PartyModel getParty() {
        return result.getParty();
      }
      public Builder setParty(proto.response.ResParty.PartyModel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasParty = true;
        result.party_ = value;
        return this;
      }
      public Builder setParty(proto.response.ResParty.PartyModel.Builder builderForValue) {
        result.hasParty = true;
        result.party_ = builderForValue.build();
        return this;
      }
      public Builder mergeParty(proto.response.ResParty.PartyModel value) {
        if (result.hasParty() &&
            result.party_ != proto.response.ResParty.PartyModel.getDefaultInstance()) {
          result.party_ =
            proto.response.ResParty.PartyModel.newBuilder(result.party_).mergeFrom(value).buildPartial();
        } else {
          result.party_ = value;
        }
        result.hasParty = true;
        return this;
      }
      public Builder clearParty() {
        result.hasParty = false;
        result.party_ = proto.response.ResParty.PartyModel.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartyJoined)
    }
    
    static {
      defaultInstance = new PartyJoined(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartyJoined)
  }
  
  public static final class PartyLeaved extends
      com.google.protobuf.GeneratedMessage {
    // Use PartyLeaved.newBuilder() to construct.
    private PartyLeaved() {
      initFields();
    }
    private PartyLeaved(boolean noInit) {}
    
    private static final PartyLeaved defaultInstance;
    public static PartyLeaved getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartyLeaved getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_PartyLeaved_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_PartyLeaved_fieldAccessorTable;
    }
    
    // optional string partyID = 1;
    public static final int PARTYID_FIELD_NUMBER = 1;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyLeaved parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaved parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.PartyLeaved prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.PartyLeaved result;
      
      // Construct using proto.msg.MsgParty.PartyLeaved.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.PartyLeaved();
        return builder;
      }
      
      protected proto.msg.MsgParty.PartyLeaved internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.PartyLeaved();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.PartyLeaved.getDescriptor();
      }
      
      public proto.msg.MsgParty.PartyLeaved getDefaultInstanceForType() {
        return proto.msg.MsgParty.PartyLeaved.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.PartyLeaved build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.PartyLeaved buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.PartyLeaved buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.PartyLeaved returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string partyID = 1;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartyLeaved)
    }
    
    static {
      defaultInstance = new PartyLeaved(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartyLeaved)
  }
  
  public static final class UserJoinedParty extends
      com.google.protobuf.GeneratedMessage {
    // Use UserJoinedParty.newBuilder() to construct.
    private UserJoinedParty() {
      initFields();
    }
    private UserJoinedParty(boolean noInit) {}
    
    private static final UserJoinedParty defaultInstance;
    public static UserJoinedParty getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserJoinedParty getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_UserJoinedParty_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_UserJoinedParty_fieldAccessorTable;
    }
    
    // optional string partyID = 1;
    public static final int PARTYID_FIELD_NUMBER = 1;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    // optional .PartyMember user = 2;
    public static final int USER_FIELD_NUMBER = 2;
    private boolean hasUser;
    private proto.response.ResParty.PartyMember user_;
    public boolean hasUser() { return hasUser; }
    public proto.response.ResParty.PartyMember getUser() { return user_; }
    
    private void initFields() {
      user_ = proto.response.ResParty.PartyMember.getDefaultInstance();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.UserJoinedParty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.UserJoinedParty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.UserJoinedParty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.UserJoinedParty result;
      
      // Construct using proto.msg.MsgParty.UserJoinedParty.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.UserJoinedParty();
        return builder;
      }
      
      protected proto.msg.MsgParty.UserJoinedParty internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.UserJoinedParty();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.UserJoinedParty.getDescriptor();
      }
      
      public proto.msg.MsgParty.UserJoinedParty getDefaultInstanceForType() {
        return proto.msg.MsgParty.UserJoinedParty.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.UserJoinedParty build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.UserJoinedParty buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.UserJoinedParty buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.UserJoinedParty returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string partyID = 1;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // optional .PartyMember user = 2;
      public boolean hasUser() {
        return result.hasUser();
      }
      public proto.response.ResParty.PartyMember getUser() {
        return result.getUser();
      }
      public Builder setUser(proto.response.ResParty.PartyMember value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasUser = true;
        result.user_ = value;
        return this;
      }
      public Builder setUser(proto.response.ResParty.PartyMember.Builder builderForValue) {
        result.hasUser = true;
        result.user_ = builderForValue.build();
        return this;
      }
      public Builder mergeUser(proto.response.ResParty.PartyMember value) {
        if (result.hasUser() &&
            result.user_ != proto.response.ResParty.PartyMember.getDefaultInstance()) {
          result.user_ =
            proto.response.ResParty.PartyMember.newBuilder(result.user_).mergeFrom(value).buildPartial();
        } else {
          result.user_ = value;
        }
        result.hasUser = true;
        return this;
      }
      public Builder clearUser() {
        result.hasUser = false;
        result.user_ = proto.response.ResParty.PartyMember.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:UserJoinedParty)
    }
    
    static {
      defaultInstance = new UserJoinedParty(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:UserJoinedParty)
  }
  
  public static final class UserLeavedParty extends
      com.google.protobuf.GeneratedMessage {
    // Use UserLeavedParty.newBuilder() to construct.
    private UserLeavedParty() {
      initFields();
    }
    private UserLeavedParty(boolean noInit) {}
    
    private static final UserLeavedParty defaultInstance;
    public static UserLeavedParty getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserLeavedParty getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_UserLeavedParty_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_UserLeavedParty_fieldAccessorTable;
    }
    
    // optional string partyID = 1;
    public static final int PARTYID_FIELD_NUMBER = 1;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    // optional uint32 userID = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private boolean hasUserID;
    private int userID_ = 0;
    public boolean hasUserID() { return hasUserID; }
    public int getUserID() { return userID_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.UserLeavedParty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.UserLeavedParty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.UserLeavedParty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.UserLeavedParty result;
      
      // Construct using proto.msg.MsgParty.UserLeavedParty.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.UserLeavedParty();
        return builder;
      }
      
      protected proto.msg.MsgParty.UserLeavedParty internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.UserLeavedParty();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.UserLeavedParty.getDescriptor();
      }
      
      public proto.msg.MsgParty.UserLeavedParty getDefaultInstanceForType() {
        return proto.msg.MsgParty.UserLeavedParty.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.UserLeavedParty build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.UserLeavedParty buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.UserLeavedParty buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.UserLeavedParty returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string partyID = 1;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // optional uint32 userID = 2;
      public boolean hasUserID() {
        return result.hasUserID();
      }
      public int getUserID() {
        return result.getUserID();
      }
      public Builder setUserID(int value) {
        result.hasUserID = true;
        result.userID_ = value;
        return this;
      }
      public Builder clearUserID() {
        result.hasUserID = false;
        result.userID_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:UserLeavedParty)
    }
    
    static {
      defaultInstance = new UserLeavedParty(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:UserLeavedParty)
  }
  
  public static final class PartyMemberStatusUpdated extends
      com.google.protobuf.GeneratedMessage {
    // Use PartyMemberStatusUpdated.newBuilder() to construct.
    private PartyMemberStatusUpdated() {
      initFields();
    }
    private PartyMemberStatusUpdated(boolean noInit) {}
    
    private static final PartyMemberStatusUpdated defaultInstance;
    public static PartyMemberStatusUpdated getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartyMemberStatusUpdated getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_PartyMemberStatusUpdated_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_PartyMemberStatusUpdated_fieldAccessorTable;
    }
    
    // optional string partyID = 1;
    public static final int PARTYID_FIELD_NUMBER = 1;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    // repeated .PartyMember users = 2;
    public static final int USERS_FIELD_NUMBER = 2;
    private java.util.List<proto.response.ResParty.PartyMember> users_ =
      java.util.Collections.emptyList();
    public java.util.List<proto.response.ResParty.PartyMember> getUsersList() {
      return users_;
    }
    public int getUsersCount() { return users_.size(); }
    public proto.response.ResParty.PartyMember getUsers(int index) {
      return users_.get(index);
    }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyMemberStatusUpdated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.PartyMemberStatusUpdated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.PartyMemberStatusUpdated result;
      
      // Construct using proto.msg.MsgParty.PartyMemberStatusUpdated.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.PartyMemberStatusUpdated();
        return builder;
      }
      
      protected proto.msg.MsgParty.PartyMemberStatusUpdated internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.PartyMemberStatusUpdated();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.PartyMemberStatusUpdated.getDescriptor();
      }
      
      public proto.msg.MsgParty.PartyMemberStatusUpdated getDefaultInstanceForType() {
        return proto.msg.MsgParty.PartyMemberStatusUpdated.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.PartyMemberStatusUpdated build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.PartyMemberStatusUpdated buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.PartyMemberStatusUpdated buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.users_ != java.util.Collections.EMPTY_LIST) {
          result.users_ =
            java.util.Collections.unmodifiableList(result.users_);
        }
        proto.msg.MsgParty.PartyMemberStatusUpdated returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string partyID = 1;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // repeated .PartyMember users = 2;
      public java.util.List<proto.response.ResParty.PartyMember> getUsersList() {
        return java.util.Collections.unmodifiableList(result.users_);
      }
      public int getUsersCount() {
        return result.getUsersCount();
      }
      public proto.response.ResParty.PartyMember getUsers(int index) {
        return result.getUsers(index);
      }
      public Builder setUsers(int index, proto.response.ResParty.PartyMember value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.users_.set(index, value);
        return this;
      }
      public Builder setUsers(int index, proto.response.ResParty.PartyMember.Builder builderForValue) {
        result.users_.set(index, builderForValue.build());
        return this;
      }
      public Builder addUsers(proto.response.ResParty.PartyMember value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.users_.isEmpty()) {
          result.users_ = new java.util.ArrayList<proto.response.ResParty.PartyMember>();
        }
        result.users_.add(value);
        return this;
      }
      public Builder addUsers(proto.response.ResParty.PartyMember.Builder builderForValue) {
        if (result.users_.isEmpty()) {
          result.users_ = new java.util.ArrayList<proto.response.ResParty.PartyMember>();
        }
        result.users_.add(builderForValue.build());
        return this;
      }
      public Builder addAllUsers(
          java.lang.Iterable<? extends proto.response.ResParty.PartyMember> values) {
        if (result.users_.isEmpty()) {
          result.users_ = new java.util.ArrayList<proto.response.ResParty.PartyMember>();
        }
        super.addAll(values, result.users_);
        return this;
      }
      public Builder clearUsers() {
        result.users_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartyMemberStatusUpdated)
    }
    
    static {
      defaultInstance = new PartyMemberStatusUpdated(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartyMemberStatusUpdated)
  }
  
  public static final class PartyInvitation extends
      com.google.protobuf.GeneratedMessage {
    // Use PartyInvitation.newBuilder() to construct.
    private PartyInvitation() {
      initFields();
    }
    private PartyInvitation(boolean noInit) {}
    
    private static final PartyInvitation defaultInstance;
    public static PartyInvitation getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartyInvitation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_PartyInvitation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_PartyInvitation_fieldAccessorTable;
    }
    
    // optional uint32 leaderID = 1;
    public static final int LEADERID_FIELD_NUMBER = 1;
    private boolean hasLeaderID;
    private int leaderID_ = 0;
    public boolean hasLeaderID() { return hasLeaderID; }
    public int getLeaderID() { return leaderID_; }
    
    // optional string leaderName = 2;
    public static final int LEADERNAME_FIELD_NUMBER = 2;
    private boolean hasLeaderName;
    private java.lang.String leaderName_ = "";
    public boolean hasLeaderName() { return hasLeaderName; }
    public java.lang.String getLeaderName() { return leaderName_; }
    
    // optional string leaderPortrait = 3;
    public static final int LEADERPORTRAIT_FIELD_NUMBER = 3;
    private boolean hasLeaderPortrait;
    private java.lang.String leaderPortrait_ = "";
    public boolean hasLeaderPortrait() { return hasLeaderPortrait; }
    public java.lang.String getLeaderPortrait() { return leaderPortrait_; }
    
    // optional string partyID = 4;
    public static final int PARTYID_FIELD_NUMBER = 4;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    // optional uint32 targetUserID = 5;
    public static final int TARGETUSERID_FIELD_NUMBER = 5;
    private boolean hasTargetUserID;
    private int targetUserID_ = 0;
    public boolean hasTargetUserID() { return hasTargetUserID; }
    public int getTargetUserID() { return targetUserID_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyInvitation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.PartyInvitation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.PartyInvitation result;
      
      // Construct using proto.msg.MsgParty.PartyInvitation.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.PartyInvitation();
        return builder;
      }
      
      protected proto.msg.MsgParty.PartyInvitation internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.PartyInvitation();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.PartyInvitation.getDescriptor();
      }
      
      public proto.msg.MsgParty.PartyInvitation getDefaultInstanceForType() {
        return proto.msg.MsgParty.PartyInvitation.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.PartyInvitation build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.PartyInvitation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.PartyInvitation buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.PartyInvitation returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 leaderID = 1;
      public boolean hasLeaderID() {
        return result.hasLeaderID();
      }
      public int getLeaderID() {
        return result.getLeaderID();
      }
      public Builder setLeaderID(int value) {
        result.hasLeaderID = true;
        result.leaderID_ = value;
        return this;
      }
      public Builder clearLeaderID() {
        result.hasLeaderID = false;
        result.leaderID_ = 0;
        return this;
      }
      
      // optional string leaderName = 2;
      public boolean hasLeaderName() {
        return result.hasLeaderName();
      }
      public java.lang.String getLeaderName() {
        return result.getLeaderName();
      }
      public Builder setLeaderName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLeaderName = true;
        result.leaderName_ = value;
        return this;
      }
      public Builder clearLeaderName() {
        result.hasLeaderName = false;
        result.leaderName_ = getDefaultInstance().getLeaderName();
        return this;
      }
      
      // optional string leaderPortrait = 3;
      public boolean hasLeaderPortrait() {
        return result.hasLeaderPortrait();
      }
      public java.lang.String getLeaderPortrait() {
        return result.getLeaderPortrait();
      }
      public Builder setLeaderPortrait(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLeaderPortrait = true;
        result.leaderPortrait_ = value;
        return this;
      }
      public Builder clearLeaderPortrait() {
        result.hasLeaderPortrait = false;
        result.leaderPortrait_ = getDefaultInstance().getLeaderPortrait();
        return this;
      }
      
      // optional string partyID = 4;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // optional uint32 targetUserID = 5;
      public boolean hasTargetUserID() {
        return result.hasTargetUserID();
      }
      public int getTargetUserID() {
        return result.getTargetUserID();
      }
      public Builder setTargetUserID(int value) {
        result.hasTargetUserID = true;
        result.targetUserID_ = value;
        return this;
      }
      public Builder clearTargetUserID() {
        result.hasTargetUserID = false;
        result.targetUserID_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartyInvitation)
    }
    
    static {
      defaultInstance = new PartyInvitation(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartyInvitation)
  }
  
  public static final class PartyInvitationDeclined extends
      com.google.protobuf.GeneratedMessage {
    // Use PartyInvitationDeclined.newBuilder() to construct.
    private PartyInvitationDeclined() {
      initFields();
    }
    private PartyInvitationDeclined(boolean noInit) {}
    
    private static final PartyInvitationDeclined defaultInstance;
    public static PartyInvitationDeclined getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartyInvitationDeclined getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_PartyInvitationDeclined_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_PartyInvitationDeclined_fieldAccessorTable;
    }
    
    // optional uint32 userID = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private boolean hasUserID;
    private int userID_ = 0;
    public boolean hasUserID() { return hasUserID; }
    public int getUserID() { return userID_; }
    
    // optional string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private boolean hasUserName;
    private java.lang.String userName_ = "";
    public boolean hasUserName() { return hasUserName; }
    public java.lang.String getUserName() { return userName_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyInvitationDeclined parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.PartyInvitationDeclined prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.PartyInvitationDeclined result;
      
      // Construct using proto.msg.MsgParty.PartyInvitationDeclined.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.PartyInvitationDeclined();
        return builder;
      }
      
      protected proto.msg.MsgParty.PartyInvitationDeclined internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.PartyInvitationDeclined();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.PartyInvitationDeclined.getDescriptor();
      }
      
      public proto.msg.MsgParty.PartyInvitationDeclined getDefaultInstanceForType() {
        return proto.msg.MsgParty.PartyInvitationDeclined.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.PartyInvitationDeclined build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.PartyInvitationDeclined buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.PartyInvitationDeclined buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.PartyInvitationDeclined returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 userID = 1;
      public boolean hasUserID() {
        return result.hasUserID();
      }
      public int getUserID() {
        return result.getUserID();
      }
      public Builder setUserID(int value) {
        result.hasUserID = true;
        result.userID_ = value;
        return this;
      }
      public Builder clearUserID() {
        result.hasUserID = false;
        result.userID_ = 0;
        return this;
      }
      
      // optional string userName = 2;
      public boolean hasUserName() {
        return result.hasUserName();
      }
      public java.lang.String getUserName() {
        return result.getUserName();
      }
      public Builder setUserName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUserName = true;
        result.userName_ = value;
        return this;
      }
      public Builder clearUserName() {
        result.hasUserName = false;
        result.userName_ = getDefaultInstance().getUserName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartyInvitationDeclined)
    }
    
    static {
      defaultInstance = new PartyInvitationDeclined(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartyInvitationDeclined)
  }
  
  public static final class PartyLeaderChanged extends
      com.google.protobuf.GeneratedMessage {
    // Use PartyLeaderChanged.newBuilder() to construct.
    private PartyLeaderChanged() {
      initFields();
    }
    private PartyLeaderChanged(boolean noInit) {}
    
    private static final PartyLeaderChanged defaultInstance;
    public static PartyLeaderChanged getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartyLeaderChanged getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_PartyLeaderChanged_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_PartyLeaderChanged_fieldAccessorTable;
    }
    
    // optional string partyID = 1;
    public static final int PARTYID_FIELD_NUMBER = 1;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    // optional uint32 leaderID = 2;
    public static final int LEADERID_FIELD_NUMBER = 2;
    private boolean hasLeaderID;
    private int leaderID_ = 0;
    public boolean hasLeaderID() { return hasLeaderID; }
    public int getLeaderID() { return leaderID_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.PartyLeaderChanged parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.PartyLeaderChanged prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.PartyLeaderChanged result;
      
      // Construct using proto.msg.MsgParty.PartyLeaderChanged.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.PartyLeaderChanged();
        return builder;
      }
      
      protected proto.msg.MsgParty.PartyLeaderChanged internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.PartyLeaderChanged();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.PartyLeaderChanged.getDescriptor();
      }
      
      public proto.msg.MsgParty.PartyLeaderChanged getDefaultInstanceForType() {
        return proto.msg.MsgParty.PartyLeaderChanged.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.PartyLeaderChanged build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.PartyLeaderChanged buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.PartyLeaderChanged buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.PartyLeaderChanged returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string partyID = 1;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // optional uint32 leaderID = 2;
      public boolean hasLeaderID() {
        return result.hasLeaderID();
      }
      public int getLeaderID() {
        return result.getLeaderID();
      }
      public Builder setLeaderID(int value) {
        result.hasLeaderID = true;
        result.leaderID_ = value;
        return this;
      }
      public Builder clearLeaderID() {
        result.hasLeaderID = false;
        result.leaderID_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartyLeaderChanged)
    }
    
    static {
      defaultInstance = new PartyLeaderChanged(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartyLeaderChanged)
  }
  
  public static final class EventInvitation extends
      com.google.protobuf.GeneratedMessage {
    // Use EventInvitation.newBuilder() to construct.
    private EventInvitation() {
      initFields();
    }
    private EventInvitation(boolean noInit) {}
    
    private static final EventInvitation defaultInstance;
    public static EventInvitation getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventInvitation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_EventInvitation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_EventInvitation_fieldAccessorTable;
    }
    
    // optional uint32 eventID = 1;
    public static final int EVENTID_FIELD_NUMBER = 1;
    private boolean hasEventID;
    private int eventID_ = 0;
    public boolean hasEventID() { return hasEventID; }
    public int getEventID() { return eventID_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.EventInvitation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.EventInvitation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.EventInvitation result;
      
      // Construct using proto.msg.MsgParty.EventInvitation.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.EventInvitation();
        return builder;
      }
      
      protected proto.msg.MsgParty.EventInvitation internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.EventInvitation();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.EventInvitation.getDescriptor();
      }
      
      public proto.msg.MsgParty.EventInvitation getDefaultInstanceForType() {
        return proto.msg.MsgParty.EventInvitation.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.EventInvitation build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.EventInvitation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.EventInvitation buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.EventInvitation returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional uint32 eventID = 1;
      public boolean hasEventID() {
        return result.hasEventID();
      }
      public int getEventID() {
        return result.getEventID();
      }
      public Builder setEventID(int value) {
        result.hasEventID = true;
        result.eventID_ = value;
        return this;
      }
      public Builder clearEventID() {
        result.hasEventID = false;
        result.eventID_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EventInvitation)
    }
    
    static {
      defaultInstance = new EventInvitation(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EventInvitation)
  }
  
  public static final class EventInvitationDeclined extends
      com.google.protobuf.GeneratedMessage {
    // Use EventInvitationDeclined.newBuilder() to construct.
    private EventInvitationDeclined() {
      initFields();
    }
    private EventInvitationDeclined(boolean noInit) {}
    
    private static final EventInvitationDeclined defaultInstance;
    public static EventInvitationDeclined getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventInvitationDeclined getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.msg.MsgParty.internal_static_EventInvitationDeclined_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.msg.MsgParty.internal_static_EventInvitationDeclined_fieldAccessorTable;
    }
    
    // optional string partyID = 1;
    public static final int PARTYID_FIELD_NUMBER = 1;
    private boolean hasPartyID;
    private java.lang.String partyID_ = "";
    public boolean hasPartyID() { return hasPartyID; }
    public java.lang.String getPartyID() { return partyID_; }
    
    // optional string text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    private void initFields() {
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.msg.MsgParty.EventInvitationDeclined parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.msg.MsgParty.EventInvitationDeclined prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private proto.msg.MsgParty.EventInvitationDeclined result;
      
      // Construct using proto.msg.MsgParty.EventInvitationDeclined.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new proto.msg.MsgParty.EventInvitationDeclined();
        return builder;
      }
      
      protected proto.msg.MsgParty.EventInvitationDeclined internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new proto.msg.MsgParty.EventInvitationDeclined();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.msg.MsgParty.EventInvitationDeclined.getDescriptor();
      }
      
      public proto.msg.MsgParty.EventInvitationDeclined getDefaultInstanceForType() {
        return proto.msg.MsgParty.EventInvitationDeclined.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public proto.msg.MsgParty.EventInvitationDeclined build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private proto.msg.MsgParty.EventInvitationDeclined buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public proto.msg.MsgParty.EventInvitationDeclined buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        proto.msg.MsgParty.EventInvitationDeclined returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // optional string partyID = 1;
      public boolean hasPartyID() {
        return result.hasPartyID();
      }
      public java.lang.String getPartyID() {
        return result.getPartyID();
      }
      public Builder setPartyID(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPartyID = true;
        result.partyID_ = value;
        return this;
      }
      public Builder clearPartyID() {
        result.hasPartyID = false;
        result.partyID_ = getDefaultInstance().getPartyID();
        return this;
      }
      
      // optional string text = 2;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EventInvitationDeclined)
    }
    
    static {
      defaultInstance = new EventInvitationDeclined(true);
      proto.msg.MsgParty.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EventInvitationDeclined)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyJoined_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartyJoined_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyLeaved_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartyLeaved_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserJoinedParty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserJoinedParty_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLeavedParty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLeavedParty_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyMemberStatusUpdated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartyMemberStatusUpdated_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyInvitation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartyInvitation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyInvitationDeclined_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartyInvitationDeclined_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartyLeaderChanged_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartyLeaderChanged_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EventInvitation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EventInvitation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EventInvitationDeclined_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EventInvitationDeclined_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017msg_party.proto\032\017res_party.proto\")\n\013Pa" +
      "rtyJoined\022\032\n\005party\030\002 \001(\0132\013.PartyModel\"\036\n" +
      "\013PartyLeaved\022\017\n\007partyID\030\001 \001(\t\">\n\017UserJoi" +
      "nedParty\022\017\n\007partyID\030\001 \001(\t\022\032\n\004user\030\002 \001(\0132" +
      "\014.PartyMember\"2\n\017UserLeavedParty\022\017\n\007part" +
      "yID\030\001 \001(\t\022\016\n\006userID\030\002 \001(\r\"H\n\030PartyMember" +
      "StatusUpdated\022\017\n\007partyID\030\001 \001(\t\022\033\n\005users\030" +
      "\002 \003(\0132\014.PartyMember\"v\n\017PartyInvitation\022\020" +
      "\n\010leaderID\030\001 \001(\r\022\022\n\nleaderName\030\002 \001(\t\022\026\n\016" +
      "leaderPortrait\030\003 \001(\t\022\017\n\007partyID\030\004 \001(\t\022\024\n",
      "\014targetUserID\030\005 \001(\r\";\n\027PartyInvitationDe" +
      "clined\022\016\n\006userID\030\001 \001(\r\022\020\n\010userName\030\002 \001(\t" +
      "\"7\n\022PartyLeaderChanged\022\017\n\007partyID\030\001 \001(\t\022" +
      "\020\n\010leaderID\030\002 \001(\r\"\"\n\017EventInvitation\022\017\n\007" +
      "eventID\030\001 \001(\r\"8\n\027EventInvitationDeclined" +
      "\022\017\n\007partyID\030\001 \001(\t\022\014\n\004text\030\002 \001(\tB\r\n\tproto" +
      ".msgH\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PartyJoined_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PartyJoined_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartyJoined_descriptor,
              new java.lang.String[] { "Party", },
              proto.msg.MsgParty.PartyJoined.class,
              proto.msg.MsgParty.PartyJoined.Builder.class);
          internal_static_PartyLeaved_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PartyLeaved_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartyLeaved_descriptor,
              new java.lang.String[] { "PartyID", },
              proto.msg.MsgParty.PartyLeaved.class,
              proto.msg.MsgParty.PartyLeaved.Builder.class);
          internal_static_UserJoinedParty_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_UserJoinedParty_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserJoinedParty_descriptor,
              new java.lang.String[] { "PartyID", "User", },
              proto.msg.MsgParty.UserJoinedParty.class,
              proto.msg.MsgParty.UserJoinedParty.Builder.class);
          internal_static_UserLeavedParty_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_UserLeavedParty_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserLeavedParty_descriptor,
              new java.lang.String[] { "PartyID", "UserID", },
              proto.msg.MsgParty.UserLeavedParty.class,
              proto.msg.MsgParty.UserLeavedParty.Builder.class);
          internal_static_PartyMemberStatusUpdated_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_PartyMemberStatusUpdated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartyMemberStatusUpdated_descriptor,
              new java.lang.String[] { "PartyID", "Users", },
              proto.msg.MsgParty.PartyMemberStatusUpdated.class,
              proto.msg.MsgParty.PartyMemberStatusUpdated.Builder.class);
          internal_static_PartyInvitation_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_PartyInvitation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartyInvitation_descriptor,
              new java.lang.String[] { "LeaderID", "LeaderName", "LeaderPortrait", "PartyID", "TargetUserID", },
              proto.msg.MsgParty.PartyInvitation.class,
              proto.msg.MsgParty.PartyInvitation.Builder.class);
          internal_static_PartyInvitationDeclined_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_PartyInvitationDeclined_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartyInvitationDeclined_descriptor,
              new java.lang.String[] { "UserID", "UserName", },
              proto.msg.MsgParty.PartyInvitationDeclined.class,
              proto.msg.MsgParty.PartyInvitationDeclined.Builder.class);
          internal_static_PartyLeaderChanged_descriptor =
            getDescriptor().getMessageTypes().get(7);
          internal_static_PartyLeaderChanged_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartyLeaderChanged_descriptor,
              new java.lang.String[] { "PartyID", "LeaderID", },
              proto.msg.MsgParty.PartyLeaderChanged.class,
              proto.msg.MsgParty.PartyLeaderChanged.Builder.class);
          internal_static_EventInvitation_descriptor =
            getDescriptor().getMessageTypes().get(8);
          internal_static_EventInvitation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EventInvitation_descriptor,
              new java.lang.String[] { "EventID", },
              proto.msg.MsgParty.EventInvitation.class,
              proto.msg.MsgParty.EventInvitation.Builder.class);
          internal_static_EventInvitationDeclined_descriptor =
            getDescriptor().getMessageTypes().get(9);
          internal_static_EventInvitationDeclined_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EventInvitationDeclined_descriptor,
              new java.lang.String[] { "PartyID", "Text", },
              proto.msg.MsgParty.EventInvitationDeclined.class,
              proto.msg.MsgParty.EventInvitationDeclined.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.response.ResParty.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
